// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package globals

type Globals struct {
	WorkspaceID *string `queryParam:"style=form,explode=true,name=workspaceId"`
	// Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
	ProjectSlug *string `queryParam:"style=form,explode=true,name=projectSlug"`
}

func (o *Globals) GetWorkspaceID() *string {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

func (o *Globals) GetProjectSlug() *string {
	if o == nil {
		return nil
	}
	return o.ProjectSlug
}
