// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ApproveProgramApplicationRequestBody struct {
	// The ID of the partner to approve.
	PartnerID string `json:"partnerId"`
	// The ID of the application to approve. If not provided, the partner's most recent pending or rejected application is used. For a partner who is already approved in the program, only a pending application is used.
	ApplicationID *string `json:"applicationId,omitempty"`
	// The ID of the group to assign the partner to. If not provided, the partner will be assigned to the group they applied to, or the program's default group if no application group is set.
	GroupID *string `json:"groupId,omitempty"`
}

func (a *ApproveProgramApplicationRequestBody) GetPartnerID() string {
	if a == nil {
		return ""
	}
	return a.PartnerID
}

func (a *ApproveProgramApplicationRequestBody) GetApplicationID() *string {
	if a == nil {
		return nil
	}
	return a.ApplicationID
}

func (a *ApproveProgramApplicationRequestBody) GetGroupID() *string {
	if a == nil {
		return nil
	}
	return a.GroupID
}

// ApproveProgramApplicationResponseBody - The approved partner
type ApproveProgramApplicationResponseBody struct {
	// The ID of the approved partner.
	PartnerID string `json:"partnerId"`
}

func (a *ApproveProgramApplicationResponseBody) GetPartnerID() string {
	if a == nil {
		return ""
	}
	return a.PartnerID
}
