// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type BulkDeleteLinksRequest struct {
	// Comma-separated list of link IDs to delete. Maximum of 100 IDs. Non-existing IDs will be ignored.
	LinkIds []string `queryParam:"style=form,explode=false,name=linkIds"`
}

func (b *BulkDeleteLinksRequest) GetLinkIds() []string {
	if b == nil {
		return []string{}
	}
	return b.LinkIds
}

// BulkDeleteLinksResponseBody - The deleted links count.
type BulkDeleteLinksResponseBody struct {
	// The number of links deleted.
	DeletedCount float64 `json:"deletedCount"`
}

func (b *BulkDeleteLinksResponseBody) GetDeletedCount() float64 {
	if b == nil {
		return 0.0
	}
	return b.DeletedCount
}
