// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dubinc/dub-go/internal/utils"
)

type CreateCommissionRequestBodyCommissionsType string

const (
	CreateCommissionRequestBodyCommissionsTypeSale CreateCommissionRequestBodyCommissionsType = "sale"
)

func (e CreateCommissionRequestBodyCommissionsType) ToPointer() *CreateCommissionRequestBodyCommissionsType {
	return &e
}
func (e *CreateCommissionRequestBodyCommissionsType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sale":
		*e = CreateCommissionRequestBodyCommissionsType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateCommissionRequestBodyCommissionsType: %v", v)
	}
}

// RequestBodyCustomer - The full customer object to associate the commission with. Useful for creating the customer on demand.
type RequestBodyCustomer struct {
	// The customer's email address.
	Email *string `json:"email,omitempty"`
	// The customer's name. If not provided, the email address will be used, and if email is not provided, a random name will be generated.
	Name *string `json:"name,omitempty"`
	// The customer's avatar URL. If not provided, a random avatar will be generated.
	Avatar *string `json:"avatar,omitempty"`
	// The customer's unique identifier your database. This is useful for associating subsequent conversion events from Dub's API to your internal systems.
	ExternalID string `json:"externalId"`
	// The customer's Stripe customer ID. This is useful for attributing recurring sale events to the partner who referred the customer.
	StripeCustomerID *string `json:"stripeCustomerId,omitempty"`
	// The customer's country in ISO 3166-1 alpha-2 format. Updating this field will only affect the customer's country in Dub's system (and has no effect on existing conversion events).
	Country string `json:"country"`
}

func (r RequestBodyCustomer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RequestBodyCustomer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"externalId", "country"}); err != nil {
		return err
	}
	return nil
}

func (r *RequestBodyCustomer) GetEmail() *string {
	if r == nil {
		return nil
	}
	return r.Email
}

func (r *RequestBodyCustomer) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *RequestBodyCustomer) GetAvatar() *string {
	if r == nil {
		return nil
	}
	return r.Avatar
}

func (r *RequestBodyCustomer) GetExternalID() string {
	if r == nil {
		return ""
	}
	return r.ExternalID
}

func (r *RequestBodyCustomer) GetStripeCustomerID() *string {
	if r == nil {
		return nil
	}
	return r.StripeCustomerID
}

func (r *RequestBodyCustomer) GetCountry() string {
	if r == nil {
		return ""
	}
	return r.Country
}

type RequestBody3 struct {
	Type CreateCommissionRequestBodyCommissionsType `json:"type"`
	// The ID of the partner to create the commission for.
	PartnerID string `json:"partnerId"`
	// The customer ID to associate the commission with. Useful if the customer was already created in a prior operation and you want to associate the commission with it.
	CustomerID *string `json:"customerId,omitempty"`
	// The full customer object to associate the commission with. Useful for creating the customer on demand.
	Customer *RequestBodyCustomer `json:"customer,omitempty"`
	// The partner link ID to associate the commission with. If not provided, default to the link with the most revenue.
	LinkID *string `json:"linkId,omitempty"`
	// When `true`, import all unimported paid Stripe invoices for the customer and create a commission for each. When `false`, create a single manual sale event using `saleAmount`.
	ImportStripeInvoices *bool `default:"false" json:"importStripeInvoices"`
	// Required when `importStripeInvoices` is `false`. The sale amount in cents for the manual sale event. Ignored when importing from Stripe.
	SaleAmount *float64 `json:"saleAmount,omitempty"`
	// Only used when `importStripeInvoices` is `false`. The date of the manual sale event. Defaults to the current date and time if not provided.
	SaleEventDate *string `json:"saleEventDate,omitempty"`
	// Only used when `importStripeInvoices` is `false`. An optional invoice ID to attach to the generated sale event and commission entry for deduplication.
	InvoiceID *string `json:"invoiceId,omitempty"`
	// Only used when `importStripeInvoices` is `false`. An optional product ID stored on the sale event metadata – will also impact commission earnings calculation (if a `Sale` `Product ID` modifier is set).
	ProductID *string `json:"productId,omitempty"`
}

func (r RequestBody3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RequestBody3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"type", "partnerId"}); err != nil {
		return err
	}
	return nil
}

func (r *RequestBody3) GetType() CreateCommissionRequestBodyCommissionsType {
	if r == nil {
		return CreateCommissionRequestBodyCommissionsType("")
	}
	return r.Type
}

func (r *RequestBody3) GetPartnerID() string {
	if r == nil {
		return ""
	}
	return r.PartnerID
}

func (r *RequestBody3) GetCustomerID() *string {
	if r == nil {
		return nil
	}
	return r.CustomerID
}

func (r *RequestBody3) GetCustomer() *RequestBodyCustomer {
	if r == nil {
		return nil
	}
	return r.Customer
}

func (r *RequestBody3) GetLinkID() *string {
	if r == nil {
		return nil
	}
	return r.LinkID
}

func (r *RequestBody3) GetImportStripeInvoices() *bool {
	if r == nil {
		return nil
	}
	return r.ImportStripeInvoices
}

func (r *RequestBody3) GetSaleAmount() *float64 {
	if r == nil {
		return nil
	}
	return r.SaleAmount
}

func (r *RequestBody3) GetSaleEventDate() *string {
	if r == nil {
		return nil
	}
	return r.SaleEventDate
}

func (r *RequestBody3) GetInvoiceID() *string {
	if r == nil {
		return nil
	}
	return r.InvoiceID
}

func (r *RequestBody3) GetProductID() *string {
	if r == nil {
		return nil
	}
	return r.ProductID
}

// #region class-body-requestbody3
// #endregion class-body-requestbody3

type CreateCommissionRequestBodyType string

const (
	CreateCommissionRequestBodyTypeLead CreateCommissionRequestBodyType = "lead"
)

func (e CreateCommissionRequestBodyType) ToPointer() *CreateCommissionRequestBodyType {
	return &e
}
func (e *CreateCommissionRequestBodyType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "lead":
		*e = CreateCommissionRequestBodyType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateCommissionRequestBodyType: %v", v)
	}
}

// Customer - The full customer object to associate the commission with. Useful for creating the customer on demand.
type Customer struct {
	// The customer's email address.
	Email *string `json:"email,omitempty"`
	// The customer's name. If not provided, the email address will be used, and if email is not provided, a random name will be generated.
	Name *string `json:"name,omitempty"`
	// The customer's avatar URL. If not provided, a random avatar will be generated.
	Avatar *string `json:"avatar,omitempty"`
	// The customer's unique identifier your database. This is useful for associating subsequent conversion events from Dub's API to your internal systems.
	ExternalID string `json:"externalId"`
	// The customer's Stripe customer ID. This is useful for attributing recurring sale events to the partner who referred the customer.
	StripeCustomerID *string `json:"stripeCustomerId,omitempty"`
	// The customer's country in ISO 3166-1 alpha-2 format. Updating this field will only affect the customer's country in Dub's system (and has no effect on existing conversion events).
	Country string `json:"country"`
}

func (c Customer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Customer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"externalId", "country"}); err != nil {
		return err
	}
	return nil
}

func (c *Customer) GetEmail() *string {
	if c == nil {
		return nil
	}
	return c.Email
}

func (c *Customer) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *Customer) GetAvatar() *string {
	if c == nil {
		return nil
	}
	return c.Avatar
}

func (c *Customer) GetExternalID() string {
	if c == nil {
		return ""
	}
	return c.ExternalID
}

func (c *Customer) GetStripeCustomerID() *string {
	if c == nil {
		return nil
	}
	return c.StripeCustomerID
}

func (c *Customer) GetCountry() string {
	if c == nil {
		return ""
	}
	return c.Country
}

type RequestBody2 struct {
	Type CreateCommissionRequestBodyType `json:"type"`
	// The ID of the partner to create the commission for.
	PartnerID string `json:"partnerId"`
	// The customer ID to associate the commission with. Useful if the customer was already created in a prior operation and you want to associate the commission with it.
	CustomerID *string `json:"customerId,omitempty"`
	// The full customer object to associate the commission with. Useful for creating the customer on demand.
	Customer *Customer `json:"customer,omitempty"`
	// The partner link ID to associate the commission with. If not provided, default to the link with the most revenue.
	LinkID *string `json:"linkId,omitempty"`
	// The date and time of the lead event. If not provided, defaults to the current date and time.
	LeadEventDate *string `json:"leadEventDate,omitempty"`
	// The name of the lead event. If not provided, defaults to 'Sign up'.
	LeadEventName *string `default:"Sign up" json:"leadEventName"`
}

func (r RequestBody2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RequestBody2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"type", "partnerId"}); err != nil {
		return err
	}
	return nil
}

func (r *RequestBody2) GetType() CreateCommissionRequestBodyType {
	if r == nil {
		return CreateCommissionRequestBodyType("")
	}
	return r.Type
}

func (r *RequestBody2) GetPartnerID() string {
	if r == nil {
		return ""
	}
	return r.PartnerID
}

func (r *RequestBody2) GetCustomerID() *string {
	if r == nil {
		return nil
	}
	return r.CustomerID
}

func (r *RequestBody2) GetCustomer() *Customer {
	if r == nil {
		return nil
	}
	return r.Customer
}

func (r *RequestBody2) GetLinkID() *string {
	if r == nil {
		return nil
	}
	return r.LinkID
}

func (r *RequestBody2) GetLeadEventDate() *string {
	if r == nil {
		return nil
	}
	return r.LeadEventDate
}

func (r *RequestBody2) GetLeadEventName() *string {
	if r == nil {
		return nil
	}
	return r.LeadEventName
}

// #region class-body-requestbody2
// #endregion class-body-requestbody2

type RequestBodyType string

const (
	RequestBodyTypeCustom RequestBodyType = "custom"
)

func (e RequestBodyType) ToPointer() *RequestBodyType {
	return &e
}
func (e *RequestBodyType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "custom":
		*e = RequestBodyType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RequestBodyType: %v", v)
	}
}

type RequestBody1 struct {
	Type RequestBodyType `json:"type"`
	// The ID of the partner to create the commission for.
	PartnerID string `json:"partnerId"`
	// The commission amount in cents.
	Amount float64 `json:"amount"`
	// If not provided, the current date will be used.
	Date *string `json:"date,omitempty"`
	// The description of the commission.
	Description *string `json:"description,omitempty"`
}

func (r RequestBody1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RequestBody1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"type", "partnerId", "amount"}); err != nil {
		return err
	}
	return nil
}

func (r *RequestBody1) GetType() RequestBodyType {
	if r == nil {
		return RequestBodyType("")
	}
	return r.Type
}

func (r *RequestBody1) GetPartnerID() string {
	if r == nil {
		return ""
	}
	return r.PartnerID
}

func (r *RequestBody1) GetAmount() float64 {
	if r == nil {
		return 0.0
	}
	return r.Amount
}

func (r *RequestBody1) GetDate() *string {
	if r == nil {
		return nil
	}
	return r.Date
}

func (r *RequestBody1) GetDescription() *string {
	if r == nil {
		return nil
	}
	return r.Description
}

// #region class-body-requestbody1
// #endregion class-body-requestbody1

type CreateCommissionRequestBodyUnionType string

const (
	CreateCommissionRequestBodyUnionTypeRequestBody1 CreateCommissionRequestBodyUnionType = "requestBody_1"
	CreateCommissionRequestBodyUnionTypeRequestBody2 CreateCommissionRequestBodyUnionType = "requestBody_2"
	CreateCommissionRequestBodyUnionTypeRequestBody3 CreateCommissionRequestBodyUnionType = "requestBody_3"
)

type CreateCommissionRequestBody struct {
	RequestBody1 *RequestBody1 `queryParam:"inline" union:"member"`
	RequestBody2 *RequestBody2 `queryParam:"inline" union:"member"`
	RequestBody3 *RequestBody3 `queryParam:"inline" union:"member"`

	Type CreateCommissionRequestBodyUnionType
}

func CreateCreateCommissionRequestBodyRequestBody1(requestBody1 RequestBody1) CreateCommissionRequestBody {
	typ := CreateCommissionRequestBodyUnionTypeRequestBody1

	return CreateCommissionRequestBody{
		RequestBody1: &requestBody1,
		Type:         typ,
	}
}

func CreateCreateCommissionRequestBodyRequestBody2(requestBody2 RequestBody2) CreateCommissionRequestBody {
	typ := CreateCommissionRequestBodyUnionTypeRequestBody2

	return CreateCommissionRequestBody{
		RequestBody2: &requestBody2,
		Type:         typ,
	}
}

func CreateCreateCommissionRequestBodyRequestBody3(requestBody3 RequestBody3) CreateCommissionRequestBody {
	typ := CreateCommissionRequestBodyUnionTypeRequestBody3

	return CreateCommissionRequestBody{
		RequestBody3: &requestBody3,
		Type:         typ,
	}
}

func (u *CreateCommissionRequestBody) UnmarshalJSON(data []byte) error {

	var requestBody1 RequestBody1 = RequestBody1{}
	if err := utils.UnmarshalJSON(data, &requestBody1, "", true, nil); err == nil {
		u.RequestBody1 = &requestBody1
		u.Type = CreateCommissionRequestBodyUnionTypeRequestBody1
		return nil
	}

	var requestBody2 RequestBody2 = RequestBody2{}
	if err := utils.UnmarshalJSON(data, &requestBody2, "", true, nil); err == nil {
		u.RequestBody2 = &requestBody2
		u.Type = CreateCommissionRequestBodyUnionTypeRequestBody2
		return nil
	}

	var requestBody3 RequestBody3 = RequestBody3{}
	if err := utils.UnmarshalJSON(data, &requestBody3, "", true, nil); err == nil {
		u.RequestBody3 = &requestBody3
		u.Type = CreateCommissionRequestBodyUnionTypeRequestBody3
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for CreateCommissionRequestBody", string(data))
}

func (u CreateCommissionRequestBody) MarshalJSON() ([]byte, error) {
	if u.RequestBody1 != nil {
		return utils.MarshalJSON(u.RequestBody1, "", true)
	}

	if u.RequestBody2 != nil {
		return utils.MarshalJSON(u.RequestBody2, "", true)
	}

	if u.RequestBody3 != nil {
		return utils.MarshalJSON(u.RequestBody3, "", true)
	}

	return nil, errors.New("could not marshal union type CreateCommissionRequestBody: all fields are null")
}

// CreateCommissionResponseBody - The request was accepted and commission creation was queued.
type CreateCommissionResponseBody struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

func (c *CreateCommissionResponseBody) GetSuccess() bool {
	if c == nil {
		return false
	}
	return c.Success
}

func (c *CreateCommissionResponseBody) GetMessage() string {
	if c == nil {
		return ""
	}
	return c.Message
}
