// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
)

// Color - The color of the tag. If not provided, a random color will be used from the list: red, yellow, green, blue, purple, brown, gray.
type Color string

const (
	ColorRed    Color = "red"
	ColorYellow Color = "yellow"
	ColorGreen  Color = "green"
	ColorBlue   Color = "blue"
	ColorPurple Color = "purple"
	ColorBrown  Color = "brown"
	ColorGray   Color = "gray"
	ColorPink   Color = "pink"
)

func (e Color) ToPointer() *Color {
	return &e
}
func (e *Color) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "red":
		fallthrough
	case "yellow":
		fallthrough
	case "green":
		fallthrough
	case "blue":
		fallthrough
	case "purple":
		fallthrough
	case "brown":
		fallthrough
	case "gray":
		fallthrough
	case "pink":
		*e = Color(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Color: %v", v)
	}
}

type CreateTagRequestBody struct {
	// The name of the tag to create.
	Name *string `json:"name,omitempty"`
	// The color of the tag. If not provided, a random color will be used from the list: red, yellow, green, blue, purple, brown, gray.
	Color *Color `json:"color,omitempty"`
	// The name of the tag to create.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Tag *string `json:"tag,omitempty"`
}

func (c *CreateTagRequestBody) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateTagRequestBody) GetColor() *Color {
	if c == nil {
		return nil
	}
	return c.Color
}

func (c *CreateTagRequestBody) GetTag() *string {
	if c == nil {
		return nil
	}
	return c.Tag
}
