// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/dubinc/dub-go/internal/utils"
)

// AccessLevel - The access level of the folder within the workspace.
type AccessLevel string

const (
	AccessLevelWrite AccessLevel = "write"
	AccessLevelRead  AccessLevel = "read"
)

func (e AccessLevel) ToPointer() *AccessLevel {
	return &e
}
func (e *AccessLevel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "write":
		fallthrough
	case "read":
		*e = AccessLevel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccessLevel: %v", v)
	}
}

type CreateFolderRequestBody struct {
	// The name of the folder.
	Name string `json:"name"`
	// The description of the folder.
	Description *string `json:"description,omitempty"`
	// The access level of the folder within the workspace.
	AccessLevel *AccessLevel `default:"null" json:"accessLevel"`
}

func (c CreateFolderRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateFolderRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateFolderRequestBody) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateFolderRequestBody) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateFolderRequestBody) GetAccessLevel() *AccessLevel {
	if c == nil {
		return nil
	}
	return c.AccessLevel
}
