// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/dubinc/dub-go/models/components"
)

type DeleteDomainGlobals struct {
	WorkspaceID string `queryParam:"style=form,explode=true,name=workspaceId"`
	// Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
	ProjectSlug *string `queryParam:"style=form,explode=true,name=projectSlug"`
}

func (o *DeleteDomainGlobals) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *DeleteDomainGlobals) GetProjectSlug() *string {
	if o == nil {
		return nil
	}
	return o.ProjectSlug
}

type DeleteDomainRequest struct {
	// The domain name.
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (o *DeleteDomainRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

// DeleteDomainResponseBody - The domain was deleted.
type DeleteDomainResponseBody struct {
	// The domain name.
	Slug string `json:"slug"`
}

func (o *DeleteDomainResponseBody) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

type DeleteDomainResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The domain was deleted.
	Object *DeleteDomainResponseBody
}

func (o *DeleteDomainResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DeleteDomainResponse) GetObject() *DeleteDomainResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
