// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteLinkRequest struct {
	// The id of the link to delete. You may use either `linkId` (obtained via `/links/info` endpoint) or `externalId` prefixed with `ext_`.
	LinkID string `pathParam:"style=simple,explode=false,name=linkId"`
}

func (d *DeleteLinkRequest) GetLinkID() string {
	if d == nil {
		return ""
	}
	return d.LinkID
}

// DeleteLinkResponseBody - The deleted link ID.
type DeleteLinkResponseBody struct {
	// The ID of the link.
	ID string `json:"id"`
}

func (d *DeleteLinkResponseBody) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}
