// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type DeleteFolderRequest struct {
	// The ID of the folder to delete.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteFolderRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

// DeleteFolderResponseBody - The deleted folder ID.
type DeleteFolderResponseBody struct {
	// The ID of the deleted folder.
	ID string `json:"id"`
}

func (d *DeleteFolderResponseBody) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}
