// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// Generated under the AGPL-3.0-only license.
// SPDX-License-Identifier: AGPL-3.0-only

package operations

type DeleteDiscountCodeRequest struct {
	// The unique ID (e.g. `dcode_...`) or alphanumeric code (e.g. `ABC123`) of the discount code to delete.
	IDOrCode string `pathParam:"style=simple,explode=false,name=idOrCode"`
}

func (d *DeleteDiscountCodeRequest) GetIDOrCode() string {
	if d == nil {
		return ""
	}
	return d.IDOrCode
}

// DeleteDiscountCodeResponseBody - The deleted discount code unique ID (e.g. `dcode_...`).
type DeleteDiscountCodeResponseBody struct {
	// The unique ID of the discount code.
	ID string `json:"id"`
}

func (d *DeleteDiscountCodeResponseBody) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}
