// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetLinkInfoRequest struct {
	Domain *string `queryParam:"style=form,explode=true,name=domain"`
	// The key of the link to retrieve. E.g. for `d.to/github`, the key is `github`.
	Key *string `queryParam:"style=form,explode=true,name=key"`
	// The unique ID of the short link.
	LinkID *string `queryParam:"style=form,explode=true,name=linkId"`
	// This is the ID of the link in the your database.
	ExternalID *string `queryParam:"style=form,explode=true,name=externalId"`
}

func (g *GetLinkInfoRequest) GetDomain() *string {
	if g == nil {
		return nil
	}
	return g.Domain
}

func (g *GetLinkInfoRequest) GetKey() *string {
	if g == nil {
		return nil
	}
	return g.Key
}

func (g *GetLinkInfoRequest) GetLinkID() *string {
	if g == nil {
		return nil
	}
	return g.LinkID
}

func (g *GetLinkInfoRequest) GetExternalID() *string {
	if g == nil {
		return nil
	}
	return g.ExternalID
}
