// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/dubinc/dub-go/models/components"
)

type GetReferersByClicksDeprecatedGlobals struct {
	WorkspaceID string `queryParam:"style=form,explode=true,name=workspaceId"`
	// Deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
	ProjectSlug *string `queryParam:"style=form,explode=true,name=projectSlug"`
}

func (o *GetReferersByClicksDeprecatedGlobals) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *GetReferersByClicksDeprecatedGlobals) GetProjectSlug() *string {
	if o == nil {
		return nil
	}
	return o.ProjectSlug
}

// GetReferersByClicksDeprecatedQueryParamInterval - The interval to retrieve analytics for. Takes precedence over start and end. If undefined, defaults to 24h.
type GetReferersByClicksDeprecatedQueryParamInterval string

const (
	GetReferersByClicksDeprecatedQueryParamIntervalOneh        GetReferersByClicksDeprecatedQueryParamInterval = "1h"
	GetReferersByClicksDeprecatedQueryParamIntervalTwentyFourh GetReferersByClicksDeprecatedQueryParamInterval = "24h"
	GetReferersByClicksDeprecatedQueryParamIntervalSevend      GetReferersByClicksDeprecatedQueryParamInterval = "7d"
	GetReferersByClicksDeprecatedQueryParamIntervalThirtyd     GetReferersByClicksDeprecatedQueryParamInterval = "30d"
	GetReferersByClicksDeprecatedQueryParamIntervalNinetyd     GetReferersByClicksDeprecatedQueryParamInterval = "90d"
	GetReferersByClicksDeprecatedQueryParamIntervalYtd         GetReferersByClicksDeprecatedQueryParamInterval = "ytd"
	GetReferersByClicksDeprecatedQueryParamIntervalOney        GetReferersByClicksDeprecatedQueryParamInterval = "1y"
	GetReferersByClicksDeprecatedQueryParamIntervalAll         GetReferersByClicksDeprecatedQueryParamInterval = "all"
)

func (e GetReferersByClicksDeprecatedQueryParamInterval) ToPointer() *GetReferersByClicksDeprecatedQueryParamInterval {
	return &e
}
func (e *GetReferersByClicksDeprecatedQueryParamInterval) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "1h":
		fallthrough
	case "24h":
		fallthrough
	case "7d":
		fallthrough
	case "30d":
		fallthrough
	case "90d":
		fallthrough
	case "ytd":
		fallthrough
	case "1y":
		fallthrough
	case "all":
		*e = GetReferersByClicksDeprecatedQueryParamInterval(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetReferersByClicksDeprecatedQueryParamInterval: %v", v)
	}
}

type GetReferersByClicksDeprecatedRequest struct {
	// The domain to filter analytics for.
	Domain *string `queryParam:"style=form,explode=true,name=domain"`
	// The short link slug.
	Key *string `queryParam:"style=form,explode=true,name=key"`
	// The unique ID of the short link on Dub.
	LinkID *string `queryParam:"style=form,explode=true,name=linkId"`
	// This is the ID of the link in the your database. Must be prefixed with 'ext_' when passed as a query parameter.
	ExternalID *string `queryParam:"style=form,explode=true,name=externalId"`
	// The interval to retrieve analytics for. Takes precedence over start and end. If undefined, defaults to 24h.
	Interval *GetReferersByClicksDeprecatedQueryParamInterval `queryParam:"style=form,explode=true,name=interval"`
	// The start date and time when to retrieve analytics from.
	Start *string `queryParam:"style=form,explode=true,name=start"`
	// The end date and time when to retrieve analytics from. If not provided, defaults to the current date.
	End *string `queryParam:"style=form,explode=true,name=end"`
	// The country to retrieve analytics for.
	Country *components.CountryCode `queryParam:"style=form,explode=true,name=country"`
	// The city to retrieve analytics for.
	City *string `queryParam:"style=form,explode=true,name=city"`
	// The device to retrieve analytics for.
	Device *string `queryParam:"style=form,explode=true,name=device"`
	// The browser to retrieve analytics for.
	Browser *string `queryParam:"style=form,explode=true,name=browser"`
	// The OS to retrieve analytics for.
	Os *string `queryParam:"style=form,explode=true,name=os"`
	// The referer to retrieve analytics for.
	Referer *string `queryParam:"style=form,explode=true,name=referer"`
	// The URL to retrieve analytics for.
	URL *string `queryParam:"style=form,explode=true,name=url"`
	// The tag ID to retrieve analytics for.
	TagID *string `queryParam:"style=form,explode=true,name=tagId"`
	// Filter for QR code scans. If true, filter for QR codes only. If false, filter for links only. If undefined, return both.
	Qr *bool `queryParam:"style=form,explode=true,name=qr"`
	// Filter for root domains. If true, filter for domains only. If false, filter for links only. If undefined, return both.
	Root *bool `queryParam:"style=form,explode=true,name=root"`
}

func (o *GetReferersByClicksDeprecatedRequest) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *GetReferersByClicksDeprecatedRequest) GetKey() *string {
	if o == nil {
		return nil
	}
	return o.Key
}

func (o *GetReferersByClicksDeprecatedRequest) GetLinkID() *string {
	if o == nil {
		return nil
	}
	return o.LinkID
}

func (o *GetReferersByClicksDeprecatedRequest) GetExternalID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalID
}

func (o *GetReferersByClicksDeprecatedRequest) GetInterval() *GetReferersByClicksDeprecatedQueryParamInterval {
	if o == nil {
		return nil
	}
	return o.Interval
}

func (o *GetReferersByClicksDeprecatedRequest) GetStart() *string {
	if o == nil {
		return nil
	}
	return o.Start
}

func (o *GetReferersByClicksDeprecatedRequest) GetEnd() *string {
	if o == nil {
		return nil
	}
	return o.End
}

func (o *GetReferersByClicksDeprecatedRequest) GetCountry() *components.CountryCode {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *GetReferersByClicksDeprecatedRequest) GetCity() *string {
	if o == nil {
		return nil
	}
	return o.City
}

func (o *GetReferersByClicksDeprecatedRequest) GetDevice() *string {
	if o == nil {
		return nil
	}
	return o.Device
}

func (o *GetReferersByClicksDeprecatedRequest) GetBrowser() *string {
	if o == nil {
		return nil
	}
	return o.Browser
}

func (o *GetReferersByClicksDeprecatedRequest) GetOs() *string {
	if o == nil {
		return nil
	}
	return o.Os
}

func (o *GetReferersByClicksDeprecatedRequest) GetReferer() *string {
	if o == nil {
		return nil
	}
	return o.Referer
}

func (o *GetReferersByClicksDeprecatedRequest) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *GetReferersByClicksDeprecatedRequest) GetTagID() *string {
	if o == nil {
		return nil
	}
	return o.TagID
}

func (o *GetReferersByClicksDeprecatedRequest) GetQr() *bool {
	if o == nil {
		return nil
	}
	return o.Qr
}

func (o *GetReferersByClicksDeprecatedRequest) GetRoot() *bool {
	if o == nil {
		return nil
	}
	return o.Root
}

type GetReferersByClicksDeprecatedResponseBody struct {
	// The name of the referer. If unknown, this will be `(direct)`
	Referer string `json:"referer"`
	// The number of clicks from this referer
	Clicks float64 `json:"clicks"`
}

func (o *GetReferersByClicksDeprecatedResponseBody) GetReferer() string {
	if o == nil {
		return ""
	}
	return o.Referer
}

func (o *GetReferersByClicksDeprecatedResponseBody) GetClicks() float64 {
	if o == nil {
		return 0.0
	}
	return o.Clicks
}

type GetReferersByClicksDeprecatedResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The top referers by number of clicks
	ResponseBodies []GetReferersByClicksDeprecatedResponseBody
}

func (o *GetReferersByClicksDeprecatedResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetReferersByClicksDeprecatedResponse) GetResponseBodies() []GetReferersByClicksDeprecatedResponseBody {
	if o == nil {
		return nil
	}
	return o.ResponseBodies
}
