// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type GetWorkspaceRequest struct {
	// The ID or slug of the workspace.
	IDOrSlug string `pathParam:"style=simple,explode=false,name=idOrSlug"`
}

func (g *GetWorkspaceRequest) GetIDOrSlug() string {
	if g == nil {
		return ""
	}
	return g.IDOrSlug
}
