// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type ListFoldersRequest struct {
	// The search term to filter the folders by.
	Search *string `queryParam:"style=form,explode=true,name=search"`
}

func (o *ListFoldersRequest) GetSearch() *string {
	if o == nil {
		return nil
	}
	return o.Search
}
