// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/dubinc/dub-go/internal/utils"
)

// RejectionReason - The reason for rejecting the partner application. This will be shared with the partner via email.
type RejectionReason string

const (
	RejectionReasonNeedsMoreDetail         RejectionReason = "needsMoreDetail"
	RejectionReasonDoesNotMeetRequirements RejectionReason = "doesNotMeetRequirements"
	RejectionReasonNotTheRightFit          RejectionReason = "notTheRightFit"
	RejectionReasonOther                   RejectionReason = "other"
)

func (e RejectionReason) ToPointer() *RejectionReason {
	return &e
}
func (e *RejectionReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "needsMoreDetail":
		fallthrough
	case "doesNotMeetRequirements":
		fallthrough
	case "notTheRightFit":
		fallthrough
	case "other":
		*e = RejectionReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RejectionReason: %v", v)
	}
}

// ReapplicationTimeframe - The mode for reapplying for the program. `instant`: The partner can reapply immediately. `standard`: The partner can reapply after 30 days. `never`: The partner can never reapply for the program. Defaults to `standard` if undefined.
type ReapplicationTimeframe string

const (
	ReapplicationTimeframeInstant  ReapplicationTimeframe = "instant"
	ReapplicationTimeframeStandard ReapplicationTimeframe = "standard"
	ReapplicationTimeframeNever    ReapplicationTimeframe = "never"
)

func (e ReapplicationTimeframe) ToPointer() *ReapplicationTimeframe {
	return &e
}
func (e *ReapplicationTimeframe) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "instant":
		fallthrough
	case "standard":
		fallthrough
	case "never":
		*e = ReapplicationTimeframe(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReapplicationTimeframe: %v", v)
	}
}

type RejectProgramApplicationRequestBody struct {
	// The ID of the partner to reject.
	PartnerID string `json:"partnerId"`
	// The reason for rejecting the partner application. This will be shared with the partner via email.
	RejectionReason *RejectionReason `json:"rejectionReason,omitempty"`
	// Additional details about the rejection. This will be shared with the partner via email.
	RejectionNote *string `json:"rejectionNote,omitempty"`
	// The mode for reapplying for the program. `instant`: The partner can reapply immediately. `standard`: The partner can reapply after 30 days. `never`: The partner can never reapply for the program. Defaults to `standard` if undefined.
	ReapplicationTimeframe *ReapplicationTimeframe `default:"standard" json:"reapplicationTimeframe"`
	// Whether to flag the partner for fraud review by the Dub team. Cannot be combined with `reapplicationTimeframe: instant`.
	FlagForFraud *bool `json:"flagForFraud,omitempty"`
	// The reason for flagging the partner for fraud. Required when flagForFraud is true.
	FlagForFraudReason *string `json:"flagForFraudReason,omitempty"`
}

func (r RejectProgramApplicationRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RejectProgramApplicationRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RejectProgramApplicationRequestBody) GetPartnerID() string {
	if r == nil {
		return ""
	}
	return r.PartnerID
}

func (r *RejectProgramApplicationRequestBody) GetRejectionReason() *RejectionReason {
	if r == nil {
		return nil
	}
	return r.RejectionReason
}

func (r *RejectProgramApplicationRequestBody) GetRejectionNote() *string {
	if r == nil {
		return nil
	}
	return r.RejectionNote
}

func (r *RejectProgramApplicationRequestBody) GetReapplicationTimeframe() *ReapplicationTimeframe {
	if r == nil {
		return nil
	}
	return r.ReapplicationTimeframe
}

func (r *RejectProgramApplicationRequestBody) GetFlagForFraud() *bool {
	if r == nil {
		return nil
	}
	return r.FlagForFraud
}

func (r *RejectProgramApplicationRequestBody) GetFlagForFraudReason() *string {
	if r == nil {
		return nil
	}
	return r.FlagForFraudReason
}

// RejectProgramApplicationResponseBody - The rejected partner
type RejectProgramApplicationResponseBody struct {
	// The ID of the rejected partner.
	PartnerID string `json:"partnerId"`
}

func (r *RejectProgramApplicationResponseBody) GetPartnerID() string {
	if r == nil {
		return ""
	}
	return r.PartnerID
}
