// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/dubinc/dub-go/internal/utils"
)

// RejectionReason - The reason for rejecting the partner application. This will be shared with the partner via email.
type RejectionReason string

const (
	RejectionReasonNeedsMoreDetail         RejectionReason = "needsMoreDetail"
	RejectionReasonDoesNotMeetRequirements RejectionReason = "doesNotMeetRequirements"
	RejectionReasonNotTheRightFit          RejectionReason = "notTheRightFit"
	RejectionReasonOther                   RejectionReason = "other"
)

func (e RejectionReason) ToPointer() *RejectionReason {
	return &e
}
func (e *RejectionReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "needsMoreDetail":
		fallthrough
	case "doesNotMeetRequirements":
		fallthrough
	case "notTheRightFit":
		fallthrough
	case "other":
		*e = RejectionReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RejectionReason: %v", v)
	}
}

type RejectPartnerRequestBody struct {
	// The ID of the partner to reject.
	PartnerID string `json:"partnerId"`
	// The reason for rejecting the partner application. This will be shared with the partner via email.
	RejectionReason *RejectionReason `json:"rejectionReason,omitempty"`
	// Additional details about the rejection. This will be shared with the partner via email.
	RejectionNote *string `json:"rejectionNote,omitempty"`
	// When true, pending enrollment is removed so the partner can submit a new application immediately.
	AllowImmediateReapply *bool `default:"false" json:"allowImmediateReapply"`
}

func (r RejectPartnerRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RejectPartnerRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RejectPartnerRequestBody) GetPartnerID() string {
	if r == nil {
		return ""
	}
	return r.PartnerID
}

func (r *RejectPartnerRequestBody) GetRejectionReason() *RejectionReason {
	if r == nil {
		return nil
	}
	return r.RejectionReason
}

func (r *RejectPartnerRequestBody) GetRejectionNote() *string {
	if r == nil {
		return nil
	}
	return r.RejectionNote
}

func (r *RejectPartnerRequestBody) GetAllowImmediateReapply() *bool {
	if r == nil {
		return nil
	}
	return r.AllowImmediateReapply
}

// RejectPartnerResponseBody - The rejected partner
type RejectPartnerResponseBody struct {
	// The ID of the rejected partner.
	PartnerID string `json:"partnerId"`
}

func (r *RejectPartnerResponseBody) GetPartnerID() string {
	if r == nil {
		return ""
	}
	return r.PartnerID
}
