// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dubinc/dub-go/internal/utils"
	"github.com/dubinc/dub-go/models/components"
)

// Event - The type of event to retrieve analytics for. Defaults to `clicks`.
type Event string

const (
	EventClicks    Event = "clicks"
	EventLeads     Event = "leads"
	EventSales     Event = "sales"
	EventComposite Event = "composite"
)

func (e Event) ToPointer() *Event {
	return &e
}
func (e *Event) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "clicks":
		fallthrough
	case "leads":
		fallthrough
	case "sales":
		fallthrough
	case "composite":
		*e = Event(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Event: %v", v)
	}
}

// QueryParamGroupBy - The parameter to group the analytics data points by. Defaults to `count` if undefined.
type QueryParamGroupBy string

const (
	QueryParamGroupByCount        QueryParamGroupBy = "count"
	QueryParamGroupByTimeseries   QueryParamGroupBy = "timeseries"
	QueryParamGroupByContinents   QueryParamGroupBy = "continents"
	QueryParamGroupByRegions      QueryParamGroupBy = "regions"
	QueryParamGroupByCountries    QueryParamGroupBy = "countries"
	QueryParamGroupByCities       QueryParamGroupBy = "cities"
	QueryParamGroupByDevices      QueryParamGroupBy = "devices"
	QueryParamGroupByBrowsers     QueryParamGroupBy = "browsers"
	QueryParamGroupByOs           QueryParamGroupBy = "os"
	QueryParamGroupByTrigger      QueryParamGroupBy = "trigger"
	QueryParamGroupByTriggers     QueryParamGroupBy = "triggers"
	QueryParamGroupByReferers     QueryParamGroupBy = "referers"
	QueryParamGroupByRefererUrls  QueryParamGroupBy = "referer_urls"
	QueryParamGroupByTopFolders   QueryParamGroupBy = "top_folders"
	QueryParamGroupByTopLinkTags  QueryParamGroupBy = "top_link_tags"
	QueryParamGroupByTopDomains   QueryParamGroupBy = "top_domains"
	QueryParamGroupByTopLinks     QueryParamGroupBy = "top_links"
	QueryParamGroupByTopUrls      QueryParamGroupBy = "top_urls"
	QueryParamGroupByTopBaseUrls  QueryParamGroupBy = "top_base_urls"
	QueryParamGroupByTopPartners  QueryParamGroupBy = "top_partners"
	QueryParamGroupByTopGroups    QueryParamGroupBy = "top_groups"
	QueryParamGroupByUtmSources   QueryParamGroupBy = "utm_sources"
	QueryParamGroupByUtmMediums   QueryParamGroupBy = "utm_mediums"
	QueryParamGroupByUtmCampaigns QueryParamGroupBy = "utm_campaigns"
	QueryParamGroupByUtmTerms     QueryParamGroupBy = "utm_terms"
	QueryParamGroupByUtmContents  QueryParamGroupBy = "utm_contents"
)

func (e QueryParamGroupBy) ToPointer() *QueryParamGroupBy {
	return &e
}
func (e *QueryParamGroupBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "count":
		fallthrough
	case "timeseries":
		fallthrough
	case "continents":
		fallthrough
	case "regions":
		fallthrough
	case "countries":
		fallthrough
	case "cities":
		fallthrough
	case "devices":
		fallthrough
	case "browsers":
		fallthrough
	case "os":
		fallthrough
	case "trigger":
		fallthrough
	case "triggers":
		fallthrough
	case "referers":
		fallthrough
	case "referer_urls":
		fallthrough
	case "top_folders":
		fallthrough
	case "top_link_tags":
		fallthrough
	case "top_domains":
		fallthrough
	case "top_links":
		fallthrough
	case "top_urls":
		fallthrough
	case "top_base_urls":
		fallthrough
	case "top_partners":
		fallthrough
	case "top_groups":
		fallthrough
	case "utm_sources":
		fallthrough
	case "utm_mediums":
		fallthrough
	case "utm_campaigns":
		fallthrough
	case "utm_terms":
		fallthrough
	case "utm_contents":
		*e = QueryParamGroupBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamGroupBy: %v", v)
	}
}

// Interval - The interval to retrieve analytics for. If undefined, defaults to 24h.
type Interval string

const (
	IntervalTwentyFourh Interval = "24h"
	IntervalSevend      Interval = "7d"
	IntervalThirtyd     Interval = "30d"
	IntervalNinetyd     Interval = "90d"
	IntervalOney        Interval = "1y"
	IntervalMtd         Interval = "mtd"
	IntervalQtd         Interval = "qtd"
	IntervalYtd         Interval = "ytd"
	IntervalAll         Interval = "all"
)

func (e Interval) ToPointer() *Interval {
	return &e
}
func (e *Interval) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "24h":
		fallthrough
	case "7d":
		fallthrough
	case "30d":
		fallthrough
	case "90d":
		fallthrough
	case "1y":
		fallthrough
	case "mtd":
		fallthrough
	case "qtd":
		fallthrough
	case "ytd":
		fallthrough
	case "all":
		*e = Interval(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Interval: %v", v)
	}
}

// SaleType - Filter sales by type: 'new' for first-time purchases, 'recurring' for repeat purchases. If undefined, returns both.
type SaleType string

const (
	SaleTypeNew       SaleType = "new"
	SaleTypeRecurring SaleType = "recurring"
)

func (e SaleType) ToPointer() *SaleType {
	return &e
}
func (e *SaleType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "new":
		fallthrough
	case "recurring":
		*e = SaleType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SaleType: %v", v)
	}
}

type RetrieveAnalyticsRequest struct {
	// The type of event to retrieve analytics for. Defaults to `clicks`.
	Event *Event `default:"clicks" queryParam:"style=form,explode=true,name=event"`
	// The parameter to group the analytics data points by. Defaults to `count` if undefined.
	GroupBy *QueryParamGroupBy `default:"count" queryParam:"style=form,explode=true,name=groupBy"`
	// The domain to filter analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `dub.co`, `dub.co,google.com`, `-spam.com`.
	Domain *string `queryParam:"style=form,explode=true,name=domain"`
	// The slug of the short link to retrieve analytics for. Must be used along with the corresponding `domain` of the short link to fetch analytics for a specific short link.
	Key *string `queryParam:"style=form,explode=true,name=key"`
	// The unique ID of the link to retrieve analytics for.Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `link_123`, `link_123,link_456`, `-link_789`.
	LinkID *string `queryParam:"style=form,explode=true,name=linkId"`
	// The ID of the link in the your database. Must be prefixed with 'ext_' when passed as a query parameter.
	ExternalID *string `queryParam:"style=form,explode=true,name=externalId"`
	// The ID of the tenant that created the link inside your system. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `tenant_123`, `tenant_123,tenant_456`, `-tenant_789`.
	TenantID *string `queryParam:"style=form,explode=true,name=tenantId"`
	// The tag ID to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `tag_123`, `tag_123,tag_456`, `-tag_789`.
	TagID *string `queryParam:"style=form,explode=true,name=tagId"`
	// The folder ID to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `folder_123`, `folder_123,folder_456`, `-folder_789`. If not provided, return analytics for all links.
	FolderID *string `queryParam:"style=form,explode=true,name=folderId"`
	// The group ID to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `grp_123`, `grp_123,grp_456`, `-grp_789`.
	GroupID *string `queryParam:"style=form,explode=true,name=groupId"`
	// The ID of the partner to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `pn_123`, `pn_123,pn_456`, `-pn_789`.
	PartnerID *string `queryParam:"style=form,explode=true,name=partnerId"`
	// The ID of the customer to retrieve analytics for.
	CustomerID *string `queryParam:"style=form,explode=true,name=customerId"`
	// The interval to retrieve analytics for. If undefined, defaults to 24h.
	Interval *Interval `queryParam:"style=form,explode=true,name=interval"`
	// The start date and time when to retrieve analytics from. If set, takes precedence over `interval`.
	Start *string `queryParam:"style=form,explode=true,name=start"`
	// The end date and time when to retrieve analytics from. If not provided, defaults to the current date. If set along with `start`, takes precedence over `interval`.
	End *string `queryParam:"style=form,explode=true,name=end"`
	// The IANA time zone code for aligning timeseries granularity (e.g. America/New_York). Defaults to UTC.
	Timezone *string `default:"UTC" queryParam:"style=form,explode=true,name=timezone"`
	// The country to retrieve analytics for. Must be passed as a 2-letter ISO 3166-1 country code (see https://d.to/geo). Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `US`, `US,BR,FR`, `-US`.
	Country *string `queryParam:"style=form,explode=true,name=country"`
	// The city to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `New York`, `New York,London`, `-New York`.
	City *string `queryParam:"style=form,explode=true,name=city"`
	// The ISO 3166-2 region code to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `NY`, `NY,CA`, `-NY`.
	Region *string `queryParam:"style=form,explode=true,name=region"`
	// The continent to retrieve analytics for. Valid values: AF, AN, AS, EU, NA, OC, SA. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `NA`, `NA,EU`, `-AS`.
	Continent *string `queryParam:"style=form,explode=true,name=continent"`
	// The device to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `Desktop`, `Mobile,Tablet`, `-Mobile`.
	Device *string `queryParam:"style=form,explode=true,name=device"`
	// The browser to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `Chrome`, `Chrome,Firefox,Safari`, `-IE`.
	Browser *string `queryParam:"style=form,explode=true,name=browser"`
	// The OS to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `Windows`, `Mac,Windows,Linux`, `-Windows`.
	Os *string `queryParam:"style=form,explode=true,name=os"`
	// The trigger to retrieve analytics for. Valid values: qr, link, pageview. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `qr`, `qr,link`, `-qr`. If undefined, returns all trigger types.
	Trigger *string `queryParam:"style=form,explode=true,name=trigger"`
	// The referer hostname to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `google.com`, `google.com,twitter.com`, `-facebook.com`.
	Referer *string `queryParam:"style=form,explode=true,name=referer"`
	// The full referer URL to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `https://google.com`, `https://google.com,https://twitter.com`, `-https://spam.com`.
	RefererURL *string `queryParam:"style=form,explode=true,name=refererUrl"`
	// The destination URL to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `https://example.com`, `https://example.com,https://other.com`, `-https://spam.com`.
	URL *string `queryParam:"style=form,explode=true,name=url"`
	// The UTM source to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `google`, `google,twitter`, `-spam`.
	UtmSource *string `queryParam:"style=form,explode=true,name=utm_source"`
	// The UTM medium to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `cpc`, `cpc,social`, `-email`.
	UtmMedium *string `queryParam:"style=form,explode=true,name=utm_medium"`
	// The UTM campaign to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`). Examples: `summer_sale`, `summer_sale,winter_sale`, `-old_campaign`.
	UtmCampaign *string `queryParam:"style=form,explode=true,name=utm_campaign"`
	// The UTM term to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`).
	UtmTerm *string `queryParam:"style=form,explode=true,name=utm_term"`
	// The UTM content to retrieve analytics for. Supports advanced filtering: single value, multiple values (comma-separated), or exclusion (prefix with `-`).
	UtmContent *string `queryParam:"style=form,explode=true,name=utm_content"`
	// Filter for root domains. If true, filter for domains only. If false, filter for links only. If undefined, return both.
	Root *bool `queryParam:"style=form,explode=true,name=root"`
	// Filter sales by type: 'new' for first-time purchases, 'recurring' for repeat purchases. If undefined, returns both.
	SaleType *SaleType `queryParam:"style=form,explode=true,name=saleType"`
	// Search the events by a custom metadata value. Only available for lead and sale events. Examples: `metadata['key']:'value'`
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Deprecated: This is automatically inferred from your workspace's defaultProgramId. The ID of the program to retrieve analytics for.
	ProgramID *string `queryParam:"style=form,explode=true,name=programId"`
	// Deprecated: Use `tagId` instead. The tag IDs to retrieve analytics for.
	TagIds *string `queryParam:"style=form,explode=true,name=tagIds"`
	// Deprecated: Use the `trigger` field instead. Filter for QR code scans. If true, filter for QR codes only. If false, filter for links only. If undefined, return both.
	Qr *bool `queryParam:"style=form,explode=true,name=qr"`
}

func (r RetrieveAnalyticsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RetrieveAnalyticsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RetrieveAnalyticsRequest) GetEvent() *Event {
	if r == nil {
		return nil
	}
	return r.Event
}

func (r *RetrieveAnalyticsRequest) GetGroupBy() *QueryParamGroupBy {
	if r == nil {
		return nil
	}
	return r.GroupBy
}

func (r *RetrieveAnalyticsRequest) GetDomain() *string {
	if r == nil {
		return nil
	}
	return r.Domain
}

func (r *RetrieveAnalyticsRequest) GetKey() *string {
	if r == nil {
		return nil
	}
	return r.Key
}

func (r *RetrieveAnalyticsRequest) GetLinkID() *string {
	if r == nil {
		return nil
	}
	return r.LinkID
}

func (r *RetrieveAnalyticsRequest) GetExternalID() *string {
	if r == nil {
		return nil
	}
	return r.ExternalID
}

func (r *RetrieveAnalyticsRequest) GetTenantID() *string {
	if r == nil {
		return nil
	}
	return r.TenantID
}

func (r *RetrieveAnalyticsRequest) GetTagID() *string {
	if r == nil {
		return nil
	}
	return r.TagID
}

func (r *RetrieveAnalyticsRequest) GetFolderID() *string {
	if r == nil {
		return nil
	}
	return r.FolderID
}

func (r *RetrieveAnalyticsRequest) GetGroupID() *string {
	if r == nil {
		return nil
	}
	return r.GroupID
}

func (r *RetrieveAnalyticsRequest) GetPartnerID() *string {
	if r == nil {
		return nil
	}
	return r.PartnerID
}

func (r *RetrieveAnalyticsRequest) GetCustomerID() *string {
	if r == nil {
		return nil
	}
	return r.CustomerID
}

func (r *RetrieveAnalyticsRequest) GetInterval() *Interval {
	if r == nil {
		return nil
	}
	return r.Interval
}

func (r *RetrieveAnalyticsRequest) GetStart() *string {
	if r == nil {
		return nil
	}
	return r.Start
}

func (r *RetrieveAnalyticsRequest) GetEnd() *string {
	if r == nil {
		return nil
	}
	return r.End
}

func (r *RetrieveAnalyticsRequest) GetTimezone() *string {
	if r == nil {
		return nil
	}
	return r.Timezone
}

func (r *RetrieveAnalyticsRequest) GetCountry() *string {
	if r == nil {
		return nil
	}
	return r.Country
}

func (r *RetrieveAnalyticsRequest) GetCity() *string {
	if r == nil {
		return nil
	}
	return r.City
}

func (r *RetrieveAnalyticsRequest) GetRegion() *string {
	if r == nil {
		return nil
	}
	return r.Region
}

func (r *RetrieveAnalyticsRequest) GetContinent() *string {
	if r == nil {
		return nil
	}
	return r.Continent
}

func (r *RetrieveAnalyticsRequest) GetDevice() *string {
	if r == nil {
		return nil
	}
	return r.Device
}

func (r *RetrieveAnalyticsRequest) GetBrowser() *string {
	if r == nil {
		return nil
	}
	return r.Browser
}

func (r *RetrieveAnalyticsRequest) GetOs() *string {
	if r == nil {
		return nil
	}
	return r.Os
}

func (r *RetrieveAnalyticsRequest) GetTrigger() *string {
	if r == nil {
		return nil
	}
	return r.Trigger
}

func (r *RetrieveAnalyticsRequest) GetReferer() *string {
	if r == nil {
		return nil
	}
	return r.Referer
}

func (r *RetrieveAnalyticsRequest) GetRefererURL() *string {
	if r == nil {
		return nil
	}
	return r.RefererURL
}

func (r *RetrieveAnalyticsRequest) GetURL() *string {
	if r == nil {
		return nil
	}
	return r.URL
}

func (r *RetrieveAnalyticsRequest) GetUtmSource() *string {
	if r == nil {
		return nil
	}
	return r.UtmSource
}

func (r *RetrieveAnalyticsRequest) GetUtmMedium() *string {
	if r == nil {
		return nil
	}
	return r.UtmMedium
}

func (r *RetrieveAnalyticsRequest) GetUtmCampaign() *string {
	if r == nil {
		return nil
	}
	return r.UtmCampaign
}

func (r *RetrieveAnalyticsRequest) GetUtmTerm() *string {
	if r == nil {
		return nil
	}
	return r.UtmTerm
}

func (r *RetrieveAnalyticsRequest) GetUtmContent() *string {
	if r == nil {
		return nil
	}
	return r.UtmContent
}

func (r *RetrieveAnalyticsRequest) GetRoot() *bool {
	if r == nil {
		return nil
	}
	return r.Root
}

func (r *RetrieveAnalyticsRequest) GetSaleType() *SaleType {
	if r == nil {
		return nil
	}
	return r.SaleType
}

func (r *RetrieveAnalyticsRequest) GetQuery() *string {
	if r == nil {
		return nil
	}
	return r.Query
}

func (r *RetrieveAnalyticsRequest) GetProgramID() *string {
	if r == nil {
		return nil
	}
	return r.ProgramID
}

func (r *RetrieveAnalyticsRequest) GetTagIds() *string {
	if r == nil {
		return nil
	}
	return r.TagIds
}

func (r *RetrieveAnalyticsRequest) GetQr() *bool {
	if r == nil {
		return nil
	}
	return r.Qr
}

type RetrieveAnalyticsResponseBodyType string

const (
	RetrieveAnalyticsResponseBodyTypeAnalyticsCount              RetrieveAnalyticsResponseBodyType = "AnalyticsCount"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTimeseries  RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsTimeseries"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsContinents  RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsContinents"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsCountries   RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsCountries"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsRegions     RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsRegions"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsCities      RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsCities"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsDevices     RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsDevices"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsBrowsers    RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsBrowsers"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsOS          RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsOS"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTriggers    RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsTriggers"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsReferers    RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsReferers"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsRefererUrls RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsRefererUrls"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTopLinks    RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsTopLinks"
	RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTopUrls     RetrieveAnalyticsResponseBodyType = "arrayOfAnalyticsTopUrls"
)

// RetrieveAnalyticsResponseBody - Analytics data
type RetrieveAnalyticsResponseBody struct {
	AnalyticsCount              *components.AnalyticsCount        `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsTimeseries  []components.AnalyticsTimeseries  `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsContinents  []components.AnalyticsContinents  `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsCountries   []components.AnalyticsCountries   `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsRegions     []components.AnalyticsRegions     `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsCities      []components.AnalyticsCities      `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsDevices     []components.AnalyticsDevices     `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsBrowsers    []components.AnalyticsBrowsers    `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsOS          []components.AnalyticsOS          `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsTriggers    []components.AnalyticsTriggers    `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsReferers    []components.AnalyticsReferers    `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsRefererUrls []components.AnalyticsRefererUrls `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsTopLinks    []components.AnalyticsTopLinks    `queryParam:"inline" union:"member"`
	ArrayOfAnalyticsTopUrls     []components.AnalyticsTopUrls     `queryParam:"inline" union:"member"`

	Type RetrieveAnalyticsResponseBodyType
}

func CreateRetrieveAnalyticsResponseBodyAnalyticsCount(analyticsCount components.AnalyticsCount) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeAnalyticsCount

	return RetrieveAnalyticsResponseBody{
		AnalyticsCount: &analyticsCount,
		Type:           typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsTimeseries(arrayOfAnalyticsTimeseries []components.AnalyticsTimeseries) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTimeseries

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsTimeseries: arrayOfAnalyticsTimeseries,
		Type:                       typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsContinents(arrayOfAnalyticsContinents []components.AnalyticsContinents) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsContinents

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsContinents: arrayOfAnalyticsContinents,
		Type:                       typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsCountries(arrayOfAnalyticsCountries []components.AnalyticsCountries) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsCountries

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsCountries: arrayOfAnalyticsCountries,
		Type:                      typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsRegions(arrayOfAnalyticsRegions []components.AnalyticsRegions) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsRegions

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsRegions: arrayOfAnalyticsRegions,
		Type:                    typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsCities(arrayOfAnalyticsCities []components.AnalyticsCities) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsCities

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsCities: arrayOfAnalyticsCities,
		Type:                   typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsDevices(arrayOfAnalyticsDevices []components.AnalyticsDevices) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsDevices

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsDevices: arrayOfAnalyticsDevices,
		Type:                    typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsBrowsers(arrayOfAnalyticsBrowsers []components.AnalyticsBrowsers) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsBrowsers

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsBrowsers: arrayOfAnalyticsBrowsers,
		Type:                     typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsOS(arrayOfAnalyticsOS []components.AnalyticsOS) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsOS

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsOS: arrayOfAnalyticsOS,
		Type:               typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsTriggers(arrayOfAnalyticsTriggers []components.AnalyticsTriggers) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTriggers

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsTriggers: arrayOfAnalyticsTriggers,
		Type:                     typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsReferers(arrayOfAnalyticsReferers []components.AnalyticsReferers) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsReferers

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsReferers: arrayOfAnalyticsReferers,
		Type:                     typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsRefererUrls(arrayOfAnalyticsRefererUrls []components.AnalyticsRefererUrls) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsRefererUrls

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsRefererUrls: arrayOfAnalyticsRefererUrls,
		Type:                        typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsTopLinks(arrayOfAnalyticsTopLinks []components.AnalyticsTopLinks) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTopLinks

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsTopLinks: arrayOfAnalyticsTopLinks,
		Type:                     typ,
	}
}

func CreateRetrieveAnalyticsResponseBodyArrayOfAnalyticsTopUrls(arrayOfAnalyticsTopUrls []components.AnalyticsTopUrls) RetrieveAnalyticsResponseBody {
	typ := RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTopUrls

	return RetrieveAnalyticsResponseBody{
		ArrayOfAnalyticsTopUrls: arrayOfAnalyticsTopUrls,
		Type:                    typ,
	}
}

func (u *RetrieveAnalyticsResponseBody) UnmarshalJSON(data []byte) error {

	var analyticsCount components.AnalyticsCount = components.AnalyticsCount{}
	if err := utils.UnmarshalJSON(data, &analyticsCount, "", true, nil); err == nil {
		u.AnalyticsCount = &analyticsCount
		u.Type = RetrieveAnalyticsResponseBodyTypeAnalyticsCount
		return nil
	}

	var arrayOfAnalyticsTimeseries []components.AnalyticsTimeseries = []components.AnalyticsTimeseries{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsTimeseries, "", true, nil); err == nil {
		u.ArrayOfAnalyticsTimeseries = arrayOfAnalyticsTimeseries
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTimeseries
		return nil
	}

	var arrayOfAnalyticsContinents []components.AnalyticsContinents = []components.AnalyticsContinents{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsContinents, "", true, nil); err == nil {
		u.ArrayOfAnalyticsContinents = arrayOfAnalyticsContinents
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsContinents
		return nil
	}

	var arrayOfAnalyticsCountries []components.AnalyticsCountries = []components.AnalyticsCountries{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsCountries, "", true, nil); err == nil {
		u.ArrayOfAnalyticsCountries = arrayOfAnalyticsCountries
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsCountries
		return nil
	}

	var arrayOfAnalyticsRegions []components.AnalyticsRegions = []components.AnalyticsRegions{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsRegions, "", true, nil); err == nil {
		u.ArrayOfAnalyticsRegions = arrayOfAnalyticsRegions
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsRegions
		return nil
	}

	var arrayOfAnalyticsCities []components.AnalyticsCities = []components.AnalyticsCities{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsCities, "", true, nil); err == nil {
		u.ArrayOfAnalyticsCities = arrayOfAnalyticsCities
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsCities
		return nil
	}

	var arrayOfAnalyticsDevices []components.AnalyticsDevices = []components.AnalyticsDevices{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsDevices, "", true, nil); err == nil {
		u.ArrayOfAnalyticsDevices = arrayOfAnalyticsDevices
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsDevices
		return nil
	}

	var arrayOfAnalyticsBrowsers []components.AnalyticsBrowsers = []components.AnalyticsBrowsers{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsBrowsers, "", true, nil); err == nil {
		u.ArrayOfAnalyticsBrowsers = arrayOfAnalyticsBrowsers
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsBrowsers
		return nil
	}

	var arrayOfAnalyticsOS []components.AnalyticsOS = []components.AnalyticsOS{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsOS, "", true, nil); err == nil {
		u.ArrayOfAnalyticsOS = arrayOfAnalyticsOS
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsOS
		return nil
	}

	var arrayOfAnalyticsTriggers []components.AnalyticsTriggers = []components.AnalyticsTriggers{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsTriggers, "", true, nil); err == nil {
		u.ArrayOfAnalyticsTriggers = arrayOfAnalyticsTriggers
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTriggers
		return nil
	}

	var arrayOfAnalyticsReferers []components.AnalyticsReferers = []components.AnalyticsReferers{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsReferers, "", true, nil); err == nil {
		u.ArrayOfAnalyticsReferers = arrayOfAnalyticsReferers
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsReferers
		return nil
	}

	var arrayOfAnalyticsRefererUrls []components.AnalyticsRefererUrls = []components.AnalyticsRefererUrls{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsRefererUrls, "", true, nil); err == nil {
		u.ArrayOfAnalyticsRefererUrls = arrayOfAnalyticsRefererUrls
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsRefererUrls
		return nil
	}

	var arrayOfAnalyticsTopLinks []components.AnalyticsTopLinks = []components.AnalyticsTopLinks{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsTopLinks, "", true, nil); err == nil {
		u.ArrayOfAnalyticsTopLinks = arrayOfAnalyticsTopLinks
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTopLinks
		return nil
	}

	var arrayOfAnalyticsTopUrls []components.AnalyticsTopUrls = []components.AnalyticsTopUrls{}
	if err := utils.UnmarshalJSON(data, &arrayOfAnalyticsTopUrls, "", true, nil); err == nil {
		u.ArrayOfAnalyticsTopUrls = arrayOfAnalyticsTopUrls
		u.Type = RetrieveAnalyticsResponseBodyTypeArrayOfAnalyticsTopUrls
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for RetrieveAnalyticsResponseBody", string(data))
}

func (u RetrieveAnalyticsResponseBody) MarshalJSON() ([]byte, error) {
	if u.AnalyticsCount != nil {
		return utils.MarshalJSON(u.AnalyticsCount, "", true)
	}

	if u.ArrayOfAnalyticsTimeseries != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsTimeseries, "", true)
	}

	if u.ArrayOfAnalyticsContinents != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsContinents, "", true)
	}

	if u.ArrayOfAnalyticsCountries != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsCountries, "", true)
	}

	if u.ArrayOfAnalyticsRegions != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsRegions, "", true)
	}

	if u.ArrayOfAnalyticsCities != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsCities, "", true)
	}

	if u.ArrayOfAnalyticsDevices != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsDevices, "", true)
	}

	if u.ArrayOfAnalyticsBrowsers != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsBrowsers, "", true)
	}

	if u.ArrayOfAnalyticsOS != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsOS, "", true)
	}

	if u.ArrayOfAnalyticsTriggers != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsTriggers, "", true)
	}

	if u.ArrayOfAnalyticsReferers != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsReferers, "", true)
	}

	if u.ArrayOfAnalyticsRefererUrls != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsRefererUrls, "", true)
	}

	if u.ArrayOfAnalyticsTopLinks != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsTopLinks, "", true)
	}

	if u.ArrayOfAnalyticsTopUrls != nil {
		return utils.MarshalJSON(u.ArrayOfAnalyticsTopUrls, "", true)
	}

	return nil, errors.New("could not marshal union type RetrieveAnalyticsResponseBody: all fields are null")
}
