// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type UpdateCustomerRequestBody struct {
	// Email of the customer in the client's app.
	Email *string `json:"email,omitempty"`
	// Name of the customer in the client's app. If not provided, a random name will be generated.
	Name *string `json:"name,omitempty"`
	// Avatar URL of the customer in the client's app.
	Avatar *string `json:"avatar,omitempty"`
	// Unique identifier for the customer in the client's app.
	ExternalID *string `json:"externalId,omitempty"`
}

func (o *UpdateCustomerRequestBody) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UpdateCustomerRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateCustomerRequestBody) GetAvatar() *string {
	if o == nil {
		return nil
	}
	return o.Avatar
}

func (o *UpdateCustomerRequestBody) GetExternalID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalID
}

type UpdateCustomerRequest struct {
	// The unique identifier of the customer in Dub.
	ID          string                     `pathParam:"style=simple,explode=false,name=id"`
	RequestBody *UpdateCustomerRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateCustomerRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateCustomerRequest) GetRequestBody() *UpdateCustomerRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

// UpdateCustomerResponseBody - The customer was updated.
type UpdateCustomerResponseBody struct {
	// The unique identifier of the customer in Dub.
	ID string `json:"id"`
	// Unique identifier for the customer in the client's app.
	ExternalID string `json:"externalId"`
	// Name of the customer.
	Name string `json:"name"`
	// Email of the customer.
	Email *string `json:"email,omitempty"`
	// Avatar URL of the customer.
	Avatar *string `json:"avatar,omitempty"`
	// The date the customer was created.
	CreatedAt string `json:"createdAt"`
}

func (o *UpdateCustomerResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateCustomerResponseBody) GetExternalID() string {
	if o == nil {
		return ""
	}
	return o.ExternalID
}

func (o *UpdateCustomerResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *UpdateCustomerResponseBody) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UpdateCustomerResponseBody) GetAvatar() *string {
	if o == nil {
		return nil
	}
	return o.Avatar
}

func (o *UpdateCustomerResponseBody) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}
