// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type UpdateWorkspaceRequestBody struct {
	Name              *string `json:"name,omitempty"`
	Slug              *string `json:"slug,omitempty"`
	Logo              *string `json:"logo,omitempty"`
	ConversionEnabled *bool   `json:"conversionEnabled,omitempty"`
}

func (o *UpdateWorkspaceRequestBody) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateWorkspaceRequestBody) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *UpdateWorkspaceRequestBody) GetLogo() *string {
	if o == nil {
		return nil
	}
	return o.Logo
}

func (o *UpdateWorkspaceRequestBody) GetConversionEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.ConversionEnabled
}

type UpdateWorkspaceRequest struct {
	// The ID or slug of the workspace to update.
	IDOrSlug    string                      `pathParam:"style=simple,explode=false,name=idOrSlug"`
	RequestBody *UpdateWorkspaceRequestBody `request:"mediaType=application/json"`
}

func (o *UpdateWorkspaceRequest) GetIDOrSlug() string {
	if o == nil {
		return ""
	}
	return o.IDOrSlug
}

func (o *UpdateWorkspaceRequest) GetRequestBody() *UpdateWorkspaceRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}
