// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

type UpdateWorkspaceRequestBody struct {
	Name              *string `json:"name,omitempty"`
	Slug              *string `json:"slug,omitempty"`
	Logo              any     `json:"logo,omitempty"`
	ConversionEnabled *bool   `json:"conversionEnabled,omitempty"`
}

func (u *UpdateWorkspaceRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateWorkspaceRequestBody) GetSlug() *string {
	if u == nil {
		return nil
	}
	return u.Slug
}

func (u *UpdateWorkspaceRequestBody) GetLogo() any {
	if u == nil {
		return nil
	}
	return u.Logo
}

func (u *UpdateWorkspaceRequestBody) GetConversionEnabled() *bool {
	if u == nil {
		return nil
	}
	return u.ConversionEnabled
}

type UpdateWorkspaceRequest struct {
	// The ID or slug of the workspace to update.
	IDOrSlug    string                      `pathParam:"style=simple,explode=false,name=idOrSlug"`
	RequestBody *UpdateWorkspaceRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateWorkspaceRequest) GetIDOrSlug() string {
	if u == nil {
		return ""
	}
	return u.IDOrSlug
}

func (u *UpdateWorkspaceRequest) GetRequestBody() *UpdateWorkspaceRequestBody {
	if u == nil {
		return nil
	}
	return u.RequestBody
}
