// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/dubinc/dub-go/internal/utils"
)

type UpsertLinkTagIdsType string

const (
	UpsertLinkTagIdsTypeStr        UpsertLinkTagIdsType = "str"
	UpsertLinkTagIdsTypeArrayOfStr UpsertLinkTagIdsType = "arrayOfStr"
)

// UpsertLinkTagIds - The unique IDs of the tags assigned to the short link.
type UpsertLinkTagIds struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type UpsertLinkTagIdsType
}

func CreateUpsertLinkTagIdsStr(str string) UpsertLinkTagIds {
	typ := UpsertLinkTagIdsTypeStr

	return UpsertLinkTagIds{
		Str:  &str,
		Type: typ,
	}
}

func CreateUpsertLinkTagIdsArrayOfStr(arrayOfStr []string) UpsertLinkTagIds {
	typ := UpsertLinkTagIdsTypeArrayOfStr

	return UpsertLinkTagIds{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *UpsertLinkTagIds) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = UpsertLinkTagIdsTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = UpsertLinkTagIdsTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpsertLinkTagIds", string(data))
}

func (u UpsertLinkTagIds) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type UpsertLinkTagIds: all fields are null")
}

type UpsertLinkTagNamesType string

const (
	UpsertLinkTagNamesTypeStr        UpsertLinkTagNamesType = "str"
	UpsertLinkTagNamesTypeArrayOfStr UpsertLinkTagNamesType = "arrayOfStr"
)

// UpsertLinkTagNames - The unique name of the tags assigned to the short link (case insensitive).
type UpsertLinkTagNames struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type UpsertLinkTagNamesType
}

func CreateUpsertLinkTagNamesStr(str string) UpsertLinkTagNames {
	typ := UpsertLinkTagNamesTypeStr

	return UpsertLinkTagNames{
		Str:  &str,
		Type: typ,
	}
}

func CreateUpsertLinkTagNamesArrayOfStr(arrayOfStr []string) UpsertLinkTagNames {
	typ := UpsertLinkTagNamesTypeArrayOfStr

	return UpsertLinkTagNames{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *UpsertLinkTagNames) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = UpsertLinkTagNamesTypeStr
		return nil
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		u.ArrayOfStr = arrayOfStr
		u.Type = UpsertLinkTagNamesTypeArrayOfStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpsertLinkTagNames", string(data))
}

func (u UpsertLinkTagNames) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type UpsertLinkTagNames: all fields are null")
}

type UpsertLinkTestVariants struct {
	URL        string  `json:"url"`
	Percentage float64 `json:"percentage"`
}

func (u *UpsertLinkTestVariants) GetURL() string {
	if u == nil {
		return ""
	}
	return u.URL
}

func (u *UpsertLinkTestVariants) GetPercentage() float64 {
	if u == nil {
		return 0.0
	}
	return u.Percentage
}

type UpsertLinkRequestBody struct {
	// The destination URL of the short link.
	URL string `json:"url"`
	// The domain of the short link (without protocol). If not provided, the primary domain for the workspace will be used (or `dub.sh` if the workspace has no domains).
	Domain *string `json:"domain,omitempty"`
	// The short link slug. If not provided, a random 7-character slug will be generated.
	Key *string `json:"key,omitempty"`
	// The length of the short link slug. Defaults to 7 if not provided. When used with `prefix`, the total length of the key will be `prefix.length + keyLength`.
	KeyLength *float64 `json:"keyLength,omitempty"`
	// The ID of the link in your database. If set, it can be used to identify the link in future API requests (must be prefixed with 'ext_' when passed as a query parameter). This key is unique across your workspace.
	ExternalID *string `json:"externalId,omitempty"`
	// The ID of the tenant that created the link inside your system. If set, it can be used to fetch all links for a tenant.
	TenantID *string `json:"tenantId,omitempty"`
	// The ID of the program the short link is associated with.
	ProgramID *string `json:"programId,omitempty"`
	// The ID of the partner the short link is associated with.
	PartnerID *string `json:"partnerId,omitempty"`
	// The prefix of the short link slug for randomly-generated keys (e.g. if prefix is `/c/`, generated keys will be in the `/c/:key` format). Will be ignored if `key` is provided.
	Prefix *string `json:"prefix,omitempty"`
	// Whether to track conversions for the short link. Defaults to `false` if not provided.
	TrackConversion *bool `json:"trackConversion,omitempty"`
	// Whether the short link is archived. Defaults to `false` if not provided.
	Archived *bool `json:"archived,omitempty"`
	// The unique IDs of the tags assigned to the short link.
	TagIds *UpsertLinkTagIds `json:"tagIds,omitempty"`
	// The unique name of the tags assigned to the short link (case insensitive).
	TagNames *UpsertLinkTagNames `json:"tagNames,omitempty"`
	// The unique ID existing folder to assign the short link to.
	FolderID *string `json:"folderId,omitempty"`
	// The comments for the short link.
	Comments *string `json:"comments,omitempty"`
	// The date and time when the short link will expire at.
	ExpiresAt *string `json:"expiresAt,omitempty"`
	// The URL to redirect to when the short link has expired.
	ExpiredURL *string `json:"expiredUrl,omitempty"`
	// The password required to access the destination URL of the short link.
	Password *string `json:"password,omitempty"`
	// Whether the short link uses Custom Link Previews feature. Defaults to `false` if not provided.
	Proxy *bool `json:"proxy,omitempty"`
	// The custom link preview title (og:title). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
	Title *string `json:"title,omitempty"`
	// The custom link preview description (og:description). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
	Description *string `json:"description,omitempty"`
	// The custom link preview image (og:image). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
	Image *string `json:"image,omitempty"`
	// The custom link preview video (og:video). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
	Video *string `json:"video,omitempty"`
	// Whether the short link uses link cloaking. Defaults to `false` if not provided.
	Rewrite *bool `json:"rewrite,omitempty"`
	// The iOS destination URL for the short link for iOS device targeting.
	Ios *string `json:"ios,omitempty"`
	// The Android destination URL for the short link for Android device targeting.
	Android *string `json:"android,omitempty"`
	// Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`. See https://d.to/geo for more information.
	Geo map[string]string `json:"geo,omitempty"`
	// Allow search engines to index your short link. Defaults to `false` if not provided. Learn more: https://d.to/noindex
	DoIndex *bool `json:"doIndex,omitempty"`
	// The UTM source of the short link. If set, this will populate or override the UTM source in the destination URL.
	UtmSource *string `json:"utm_source,omitempty"`
	// The UTM medium of the short link. If set, this will populate or override the UTM medium in the destination URL.
	UtmMedium *string `json:"utm_medium,omitempty"`
	// The UTM campaign of the short link. If set, this will populate or override the UTM campaign in the destination URL.
	UtmCampaign *string `json:"utm_campaign,omitempty"`
	// The UTM term of the short link. If set, this will populate or override the UTM term in the destination URL.
	UtmTerm *string `json:"utm_term,omitempty"`
	// The UTM content of the short link. If set, this will populate or override the UTM content in the destination URL.
	UtmContent *string `json:"utm_content,omitempty"`
	// The referral tag of the short link. If set, this will populate or override the `ref` query parameter in the destination URL.
	Ref *string `json:"ref,omitempty"`
	// An array of webhook IDs to trigger when the link is clicked. These webhooks will receive click event data.
	WebhookIds []string `json:"webhookIds,omitempty"`
	// An array of A/B test URLs and the percentage of traffic to send to each URL.
	TestVariants []UpsertLinkTestVariants `json:"testVariants,omitempty"`
	// The date and time when the tests started.
	TestStartedAt *string `json:"testStartedAt,omitempty"`
	// The date and time when the tests were or will be completed.
	TestCompletedAt *string `json:"testCompletedAt,omitempty"`
	// Deprecated: Use `dashboard` instead. Whether the short link's stats are publicly accessible. Defaults to `false` if not provided.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	PublicStats *bool `json:"publicStats,omitempty"`
	// Deprecated: Use `tagIds` instead. The unique ID of the tag assigned to the short link.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	TagID *string `json:"tagId,omitempty"`
}

func (u *UpsertLinkRequestBody) GetURL() string {
	if u == nil {
		return ""
	}
	return u.URL
}

func (u *UpsertLinkRequestBody) GetDomain() *string {
	if u == nil {
		return nil
	}
	return u.Domain
}

func (u *UpsertLinkRequestBody) GetKey() *string {
	if u == nil {
		return nil
	}
	return u.Key
}

func (u *UpsertLinkRequestBody) GetKeyLength() *float64 {
	if u == nil {
		return nil
	}
	return u.KeyLength
}

func (u *UpsertLinkRequestBody) GetExternalID() *string {
	if u == nil {
		return nil
	}
	return u.ExternalID
}

func (u *UpsertLinkRequestBody) GetTenantID() *string {
	if u == nil {
		return nil
	}
	return u.TenantID
}

func (u *UpsertLinkRequestBody) GetProgramID() *string {
	if u == nil {
		return nil
	}
	return u.ProgramID
}

func (u *UpsertLinkRequestBody) GetPartnerID() *string {
	if u == nil {
		return nil
	}
	return u.PartnerID
}

func (u *UpsertLinkRequestBody) GetPrefix() *string {
	if u == nil {
		return nil
	}
	return u.Prefix
}

func (u *UpsertLinkRequestBody) GetTrackConversion() *bool {
	if u == nil {
		return nil
	}
	return u.TrackConversion
}

func (u *UpsertLinkRequestBody) GetArchived() *bool {
	if u == nil {
		return nil
	}
	return u.Archived
}

func (u *UpsertLinkRequestBody) GetTagIds() *UpsertLinkTagIds {
	if u == nil {
		return nil
	}
	return u.TagIds
}

func (u *UpsertLinkRequestBody) GetTagNames() *UpsertLinkTagNames {
	if u == nil {
		return nil
	}
	return u.TagNames
}

func (u *UpsertLinkRequestBody) GetFolderID() *string {
	if u == nil {
		return nil
	}
	return u.FolderID
}

func (u *UpsertLinkRequestBody) GetComments() *string {
	if u == nil {
		return nil
	}
	return u.Comments
}

func (u *UpsertLinkRequestBody) GetExpiresAt() *string {
	if u == nil {
		return nil
	}
	return u.ExpiresAt
}

func (u *UpsertLinkRequestBody) GetExpiredURL() *string {
	if u == nil {
		return nil
	}
	return u.ExpiredURL
}

func (u *UpsertLinkRequestBody) GetPassword() *string {
	if u == nil {
		return nil
	}
	return u.Password
}

func (u *UpsertLinkRequestBody) GetProxy() *bool {
	if u == nil {
		return nil
	}
	return u.Proxy
}

func (u *UpsertLinkRequestBody) GetTitle() *string {
	if u == nil {
		return nil
	}
	return u.Title
}

func (u *UpsertLinkRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpsertLinkRequestBody) GetImage() *string {
	if u == nil {
		return nil
	}
	return u.Image
}

func (u *UpsertLinkRequestBody) GetVideo() *string {
	if u == nil {
		return nil
	}
	return u.Video
}

func (u *UpsertLinkRequestBody) GetRewrite() *bool {
	if u == nil {
		return nil
	}
	return u.Rewrite
}

func (u *UpsertLinkRequestBody) GetIos() *string {
	if u == nil {
		return nil
	}
	return u.Ios
}

func (u *UpsertLinkRequestBody) GetAndroid() *string {
	if u == nil {
		return nil
	}
	return u.Android
}

func (u *UpsertLinkRequestBody) GetGeo() map[string]string {
	if u == nil {
		return nil
	}
	return u.Geo
}

func (u *UpsertLinkRequestBody) GetDoIndex() *bool {
	if u == nil {
		return nil
	}
	return u.DoIndex
}

func (u *UpsertLinkRequestBody) GetUtmSource() *string {
	if u == nil {
		return nil
	}
	return u.UtmSource
}

func (u *UpsertLinkRequestBody) GetUtmMedium() *string {
	if u == nil {
		return nil
	}
	return u.UtmMedium
}

func (u *UpsertLinkRequestBody) GetUtmCampaign() *string {
	if u == nil {
		return nil
	}
	return u.UtmCampaign
}

func (u *UpsertLinkRequestBody) GetUtmTerm() *string {
	if u == nil {
		return nil
	}
	return u.UtmTerm
}

func (u *UpsertLinkRequestBody) GetUtmContent() *string {
	if u == nil {
		return nil
	}
	return u.UtmContent
}

func (u *UpsertLinkRequestBody) GetRef() *string {
	if u == nil {
		return nil
	}
	return u.Ref
}

func (u *UpsertLinkRequestBody) GetWebhookIds() []string {
	if u == nil {
		return nil
	}
	return u.WebhookIds
}

func (u *UpsertLinkRequestBody) GetTestVariants() []UpsertLinkTestVariants {
	if u == nil {
		return nil
	}
	return u.TestVariants
}

func (u *UpsertLinkRequestBody) GetTestStartedAt() *string {
	if u == nil {
		return nil
	}
	return u.TestStartedAt
}

func (u *UpsertLinkRequestBody) GetTestCompletedAt() *string {
	if u == nil {
		return nil
	}
	return u.TestCompletedAt
}

func (u *UpsertLinkRequestBody) GetPublicStats() *bool {
	if u == nil {
		return nil
	}
	return u.PublicStats
}

func (u *UpsertLinkRequestBody) GetTagID() *string {
	if u == nil {
		return nil
	}
	return u.TagID
}
