// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

// RateLimitExceededCode - A short code indicating the error code returned.
type RateLimitExceededCode string

const (
	RateLimitExceededCodeRateLimitExceeded RateLimitExceededCode = "rate_limit_exceeded"
)

func (e RateLimitExceededCode) ToPointer() *RateLimitExceededCode {
	return &e
}
func (e *RateLimitExceededCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "rate_limit_exceeded":
		*e = RateLimitExceededCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RateLimitExceededCode: %v", v)
	}
}

type RateLimitExceededError struct {
	// A short code indicating the error code returned.
	Code RateLimitExceededCode `json:"code"`
	// A human readable explanation of what went wrong.
	Message string `json:"message"`
	// A link to our documentation with more details about this error code
	DocURL *string `json:"doc_url,omitempty"`
}

func (r *RateLimitExceededError) GetCode() RateLimitExceededCode {
	if r == nil {
		return RateLimitExceededCode("")
	}
	return r.Code
}

func (r *RateLimitExceededError) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *RateLimitExceededError) GetDocURL() *string {
	if r == nil {
		return nil
	}
	return r.DocURL
}

// RateLimitExceeded - The user has sent too many requests in a given amount of time ("rate limiting")
type RateLimitExceeded struct {
	Error_ RateLimitExceededError `json:"error"`
}

var _ error = &RateLimitExceeded{}

func (e *RateLimitExceeded) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
