// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dubinc/dub-go/internal/utils"
)

type AnalyticsReferers struct {
	// The name of the referer. If unknown, this will be `(direct)`
	Referer string `json:"referer"`
	// The number of clicks from this referer
	Clicks *float64 `default:"0" json:"clicks"`
	// The number of leads from this referer
	Leads *float64 `default:"0" json:"leads"`
	// The number of sales from this referer
	Sales *float64 `default:"0" json:"sales"`
	// The total amount of sales from this referer, in cents
	SaleAmount *float64 `default:"0" json:"saleAmount"`
}

func (a AnalyticsReferers) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnalyticsReferers) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"referer"}); err != nil {
		return err
	}
	return nil
}

func (a *AnalyticsReferers) GetReferer() string {
	if a == nil {
		return ""
	}
	return a.Referer
}

func (a *AnalyticsReferers) GetClicks() *float64 {
	if a == nil {
		return nil
	}
	return a.Clicks
}

func (a *AnalyticsReferers) GetLeads() *float64 {
	if a == nil {
		return nil
	}
	return a.Leads
}

func (a *AnalyticsReferers) GetSales() *float64 {
	if a == nil {
		return nil
	}
	return a.Sales
}

func (a *AnalyticsReferers) GetSaleAmount() *float64 {
	if a == nil {
		return nil
	}
	return a.SaleAmount
}
