// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/dubinc/dub-go/internal/utils"
)

type AnalyticsRegionsCity string

const (
	AnalyticsRegionsCityWildcard AnalyticsRegionsCity = "*"
)

func (e AnalyticsRegionsCity) ToPointer() *AnalyticsRegionsCity {
	return &e
}
func (e *AnalyticsRegionsCity) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "*":
		*e = AnalyticsRegionsCity(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AnalyticsRegionsCity: %v", v)
	}
}

type AnalyticsRegions struct {
	// The 2-letter ISO 3166-1 country code of the country. Learn more: https://d.to/geo
	Country string `json:"country"`
	// The 2-letter ISO 3166-2 region code of the region.
	Region string                `json:"region"`
	City   *AnalyticsRegionsCity `default:"*" json:"city"`
	// The number of clicks from this region
	Clicks *float64 `default:"0" json:"clicks"`
	// The number of leads from this region
	Leads *float64 `default:"0" json:"leads"`
	// The number of sales from this region
	Sales *float64 `default:"0" json:"sales"`
	// The total amount of sales from this region, in cents
	SaleAmount *float64 `default:"0" json:"saleAmount"`
}

func (a AnalyticsRegions) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnalyticsRegions) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"country", "region"}); err != nil {
		return err
	}
	return nil
}

func (a *AnalyticsRegions) GetCountry() string {
	if a == nil {
		return ""
	}
	return a.Country
}

func (a *AnalyticsRegions) GetRegion() string {
	if a == nil {
		return ""
	}
	return a.Region
}

func (a *AnalyticsRegions) GetCity() *AnalyticsRegionsCity {
	if a == nil {
		return nil
	}
	return a.City
}

func (a *AnalyticsRegions) GetClicks() *float64 {
	if a == nil {
		return nil
	}
	return a.Clicks
}

func (a *AnalyticsRegions) GetLeads() *float64 {
	if a == nil {
		return nil
	}
	return a.Leads
}

func (a *AnalyticsRegions) GetSales() *float64 {
	if a == nil {
		return nil
	}
	return a.Sales
}

func (a *AnalyticsRegions) GetSaleAmount() *float64 {
	if a == nil {
		return nil
	}
	return a.SaleAmount
}
