// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dubinc/dub-go/internal/utils"
)

type AnalyticsRefererUrls struct {
	// The full URL of the referer. If unknown, this will be `(direct)`
	RefererURL string `json:"refererUrl"`
	// The number of clicks from this referer to this URL
	Clicks *float64 `default:"0" json:"clicks"`
	// The number of leads from this referer to this URL
	Leads *float64 `default:"0" json:"leads"`
	// The number of sales from this referer to this URL
	Sales *float64 `default:"0" json:"sales"`
	// The total amount of sales from this referer to this URL, in cents
	SaleAmount *float64 `default:"0" json:"saleAmount"`
}

func (a AnalyticsRefererUrls) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnalyticsRefererUrls) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"refererUrl"}); err != nil {
		return err
	}
	return nil
}

func (a *AnalyticsRefererUrls) GetRefererURL() string {
	if a == nil {
		return ""
	}
	return a.RefererURL
}

func (a *AnalyticsRefererUrls) GetClicks() *float64 {
	if a == nil {
		return nil
	}
	return a.Clicks
}

func (a *AnalyticsRefererUrls) GetLeads() *float64 {
	if a == nil {
		return nil
	}
	return a.Leads
}

func (a *AnalyticsRefererUrls) GetSales() *float64 {
	if a == nil {
		return nil
	}
	return a.Sales
}

func (a *AnalyticsRefererUrls) GetSaleAmount() *float64 {
	if a == nil {
		return nil
	}
	return a.SaleAmount
}
