// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ClicksCount struct {
	// The total number of clicks
	Clicks float64 `json:"clicks"`
}

func (o *ClicksCount) GetClicks() float64 {
	if o == nil {
		return 0.0
	}
	return o.Clicks
}
