// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ClicksTopUrls struct {
	// The destination URL
	URL string `json:"url"`
	// The number of clicks from this URL
	Clicks float64 `json:"clicks"`
}

func (o *ClicksTopUrls) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *ClicksTopUrls) GetClicks() float64 {
	if o == nil {
		return 0.0
	}
	return o.Clicks
}
