// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type LeadsTopUrls struct {
	// The destination URL
	URL string `json:"url"`
	// The number of leads from this URL
	Leads float64 `json:"leads"`
}

func (o *LeadsTopUrls) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *LeadsTopUrls) GetLeads() float64 {
	if o == nil {
		return 0.0
	}
	return o.Leads
}
