// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/dubinc/dub-go/internal/utils"
)

type Three string

const (
	ThreeLinkDeleted Three = "link.deleted"
)

func (e Three) ToPointer() *Three {
	return &e
}
func (e *Three) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "link.deleted":
		*e = Three(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Three: %v", v)
	}
}

type Two string

const (
	TwoLinkUpdated Two = "link.updated"
)

func (e Two) ToPointer() *Two {
	return &e
}
func (e *Two) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "link.updated":
		*e = Two(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Two: %v", v)
	}
}

type One string

const (
	OneLinkCreated One = "link.created"
)

func (e One) ToPointer() *One {
	return &e
}
func (e *One) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "link.created":
		*e = One(v)
		return nil
	default:
		return fmt.Errorf("invalid value for One: %v", v)
	}
}

type EventType string

const (
	EventTypeOne   EventType = "1"
	EventTypeTwo   EventType = "2"
	EventTypeThree EventType = "3"
)

type Event struct {
	One   *One   `queryParam:"inline" union:"member"`
	Two   *Two   `queryParam:"inline" union:"member"`
	Three *Three `queryParam:"inline" union:"member"`

	Type EventType
}

func CreateEventOne(one One) Event {
	typ := EventTypeOne

	return Event{
		One:  &one,
		Type: typ,
	}
}

func CreateEventTwo(two Two) Event {
	typ := EventTypeTwo

	return Event{
		Two:  &two,
		Type: typ,
	}
}

func CreateEventThree(three Three) Event {
	typ := EventTypeThree

	return Event{
		Three: &three,
		Type:  typ,
	}
}

func (u *Event) UnmarshalJSON(data []byte) error {

	var one One = One("")
	if err := utils.UnmarshalJSON(data, &one, "", true, nil); err == nil {
		u.One = &one
		u.Type = EventTypeOne
		return nil
	}

	var two Two = Two("")
	if err := utils.UnmarshalJSON(data, &two, "", true, nil); err == nil {
		u.Two = &two
		u.Type = EventTypeTwo
		return nil
	}

	var three Three = Three("")
	if err := utils.UnmarshalJSON(data, &three, "", true, nil); err == nil {
		u.Three = &three
		u.Type = EventTypeThree
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Event", string(data))
}

func (u Event) MarshalJSON() ([]byte, error) {
	if u.One != nil {
		return utils.MarshalJSON(u.One, "", true)
	}

	if u.Two != nil {
		return utils.MarshalJSON(u.Two, "", true)
	}

	if u.Three != nil {
		return utils.MarshalJSON(u.Three, "", true)
	}

	return nil, errors.New("could not marshal union type Event: all fields are null")
}

type LinkWebhookEventTestVariants struct {
	URL        string  `json:"url"`
	Percentage float64 `json:"percentage"`
}

func (l LinkWebhookEventTestVariants) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LinkWebhookEventTestVariants) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"url", "percentage"}); err != nil {
		return err
	}
	return nil
}

func (l *LinkWebhookEventTestVariants) GetURL() string {
	if l == nil {
		return ""
	}
	return l.URL
}

func (l *LinkWebhookEventTestVariants) GetPercentage() float64 {
	if l == nil {
		return 0.0
	}
	return l.Percentage
}

type Data struct {
	// The unique ID of the short link.
	ID string `json:"id"`
	// The domain of the short link. If not provided, the primary domain for the workspace will be used (or `dub.sh` if the workspace has no domains).
	Domain string `json:"domain"`
	// The short link slug. If not provided, a random 7-character slug will be generated.
	Key             string `json:"key"`
	URL             string `json:"url"`
	TrackConversion bool   `json:"trackConversion"`
	// The ID of the link in your database. If set, it can be used to identify the link in future API requests (must be prefixed with 'ext_' when passed as a query parameter). This key is unique across your workspace.
	ExternalID *string `json:"externalId"`
	// The ID of the tenant that created the link inside your system. If set, it can be used to fetch all links for a tenant.
	TenantID *string `json:"tenantId"`
	// The ID of the program the short link is associated with.
	ProgramID *string `json:"programId"`
	// The ID of the partner the short link is associated with.
	PartnerID  *string `json:"partnerId"`
	Archived   bool    `json:"archived"`
	ExpiresAt  string  `json:"expiresAt"`
	ExpiredURL *string `json:"expiredUrl"`
	DisabledAt string  `json:"disabledAt"`
	// The password required to access the destination URL of the short link.
	Password *string `json:"password"`
	Proxy    bool    `json:"proxy"`
	// The title of the short link. Will be used for Custom Link Previews if `proxy` is true.
	Title *string `json:"title"`
	// The description of the short link. Will be used for Custom Link Previews if `proxy` is true.
	Description *string `json:"description"`
	// The image of the short link. Will be used for Custom Link Previews if `proxy` is true.
	Image *string `json:"image"`
	// The custom link preview video (og:video). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
	Video   *string `json:"video"`
	Rewrite bool    `json:"rewrite"`
	DoIndex bool    `json:"doIndex"`
	// The iOS destination URL for the short link for iOS device targeting.
	Ios *string `json:"ios"`
	// The Android destination URL for the short link for Android device targeting.
	Android *string `json:"android"`
	// Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`. See https://d.to/geo for more information.
	Geo         map[string]string `json:"geo"`
	PublicStats bool              `json:"publicStats"`
	// The tags assigned to the short link.
	Tags []LinkTagSchema `json:"tags"`
	// The unique ID of the folder assigned to the short link.
	FolderID *string `json:"folderId"`
	// The IDs of the webhooks that the short link is associated with.
	WebhookIds []string `json:"webhookIds"`
	// The comments for the short link.
	Comments *string `json:"comments"`
	// The full URL of the short link, including the https protocol (e.g. `https://dub.sh/try`).
	ShortLink string `json:"shortLink"`
	// The full URL of the QR code for the short link (e.g. `https://api.dub.co/qr?url=https://dub.sh/try`).
	QrCode string `json:"qrCode"`
	// The UTM source of the short link.
	UtmSource *string `json:"utm_source"`
	// The UTM medium of the short link.
	UtmMedium *string `json:"utm_medium"`
	// The UTM campaign of the short link.
	UtmCampaign *string `json:"utm_campaign"`
	// The UTM term of the short link.
	UtmTerm *string `json:"utm_term"`
	// The UTM content of the short link.
	UtmContent *string `json:"utm_content"`
	// An array of A/B test URLs and the percentage of traffic to send to each URL.
	TestVariants    []LinkWebhookEventTestVariants `json:"testVariants,omitempty"`
	TestStartedAt   string                         `json:"testStartedAt"`
	TestCompletedAt string                         `json:"testCompletedAt"`
	UserID          *string                        `json:"userId"`
	// The workspace ID of the short link.
	WorkspaceID string `json:"workspaceId"`
	// The number of clicks on the short link.
	Clicks *float64 `default:"0" json:"clicks"`
	// The number of leads the short link has generated.
	Leads *float64 `default:"0" json:"leads"`
	// The number of leads that converted to paying customers.
	Conversions *float64 `default:"0" json:"conversions"`
	// The total number of sales (includes recurring sales) generated by the short link.
	Sales *float64 `default:"0" json:"sales"`
	// The total dollar value of sales (in cents) generated by the short link.
	SaleAmount  *float64 `default:"0" json:"saleAmount"`
	LastClicked string   `json:"lastClicked"`
	CreatedAt   string   `json:"createdAt"`
	UpdatedAt   string   `json:"updatedAt"`
	// Deprecated: Use `tags` instead. The unique ID of the tag assigned to the short link.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	TagID *string `json:"tagId"`
	// Deprecated: Use `workspaceId` instead. The project ID of the short link.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ProjectID string `json:"projectId"`
}

func (d Data) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *Data) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"id", "domain", "key", "url", "trackConversion", "archived", "expiresAt", "disabledAt", "proxy", "rewrite", "doIndex", "publicStats", "webhookIds", "shortLink", "qrCode", "testStartedAt", "testCompletedAt", "workspaceId", "lastClicked", "createdAt", "updatedAt", "projectId"}); err != nil {
		return err
	}
	return nil
}

func (d *Data) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *Data) GetDomain() string {
	if d == nil {
		return ""
	}
	return d.Domain
}

func (d *Data) GetKey() string {
	if d == nil {
		return ""
	}
	return d.Key
}

func (d *Data) GetURL() string {
	if d == nil {
		return ""
	}
	return d.URL
}

func (d *Data) GetTrackConversion() bool {
	if d == nil {
		return false
	}
	return d.TrackConversion
}

func (d *Data) GetExternalID() *string {
	if d == nil {
		return nil
	}
	return d.ExternalID
}

func (d *Data) GetTenantID() *string {
	if d == nil {
		return nil
	}
	return d.TenantID
}

func (d *Data) GetProgramID() *string {
	if d == nil {
		return nil
	}
	return d.ProgramID
}

func (d *Data) GetPartnerID() *string {
	if d == nil {
		return nil
	}
	return d.PartnerID
}

func (d *Data) GetArchived() bool {
	if d == nil {
		return false
	}
	return d.Archived
}

func (d *Data) GetExpiresAt() string {
	if d == nil {
		return ""
	}
	return d.ExpiresAt
}

func (d *Data) GetExpiredURL() *string {
	if d == nil {
		return nil
	}
	return d.ExpiredURL
}

func (d *Data) GetDisabledAt() string {
	if d == nil {
		return ""
	}
	return d.DisabledAt
}

func (d *Data) GetPassword() *string {
	if d == nil {
		return nil
	}
	return d.Password
}

func (d *Data) GetProxy() bool {
	if d == nil {
		return false
	}
	return d.Proxy
}

func (d *Data) GetTitle() *string {
	if d == nil {
		return nil
	}
	return d.Title
}

func (d *Data) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}

func (d *Data) GetImage() *string {
	if d == nil {
		return nil
	}
	return d.Image
}

func (d *Data) GetVideo() *string {
	if d == nil {
		return nil
	}
	return d.Video
}

func (d *Data) GetRewrite() bool {
	if d == nil {
		return false
	}
	return d.Rewrite
}

func (d *Data) GetDoIndex() bool {
	if d == nil {
		return false
	}
	return d.DoIndex
}

func (d *Data) GetIos() *string {
	if d == nil {
		return nil
	}
	return d.Ios
}

func (d *Data) GetAndroid() *string {
	if d == nil {
		return nil
	}
	return d.Android
}

func (d *Data) GetGeo() map[string]string {
	if d == nil {
		return nil
	}
	return d.Geo
}

func (d *Data) GetPublicStats() bool {
	if d == nil {
		return false
	}
	return d.PublicStats
}

func (d *Data) GetTags() []LinkTagSchema {
	if d == nil {
		return nil
	}
	return d.Tags
}

func (d *Data) GetFolderID() *string {
	if d == nil {
		return nil
	}
	return d.FolderID
}

func (d *Data) GetWebhookIds() []string {
	if d == nil {
		return []string{}
	}
	return d.WebhookIds
}

func (d *Data) GetComments() *string {
	if d == nil {
		return nil
	}
	return d.Comments
}

func (d *Data) GetShortLink() string {
	if d == nil {
		return ""
	}
	return d.ShortLink
}

func (d *Data) GetQrCode() string {
	if d == nil {
		return ""
	}
	return d.QrCode
}

func (d *Data) GetUtmSource() *string {
	if d == nil {
		return nil
	}
	return d.UtmSource
}

func (d *Data) GetUtmMedium() *string {
	if d == nil {
		return nil
	}
	return d.UtmMedium
}

func (d *Data) GetUtmCampaign() *string {
	if d == nil {
		return nil
	}
	return d.UtmCampaign
}

func (d *Data) GetUtmTerm() *string {
	if d == nil {
		return nil
	}
	return d.UtmTerm
}

func (d *Data) GetUtmContent() *string {
	if d == nil {
		return nil
	}
	return d.UtmContent
}

func (d *Data) GetTestVariants() []LinkWebhookEventTestVariants {
	if d == nil {
		return nil
	}
	return d.TestVariants
}

func (d *Data) GetTestStartedAt() string {
	if d == nil {
		return ""
	}
	return d.TestStartedAt
}

func (d *Data) GetTestCompletedAt() string {
	if d == nil {
		return ""
	}
	return d.TestCompletedAt
}

func (d *Data) GetUserID() *string {
	if d == nil {
		return nil
	}
	return d.UserID
}

func (d *Data) GetWorkspaceID() string {
	if d == nil {
		return ""
	}
	return d.WorkspaceID
}

func (d *Data) GetClicks() *float64 {
	if d == nil {
		return nil
	}
	return d.Clicks
}

func (d *Data) GetLeads() *float64 {
	if d == nil {
		return nil
	}
	return d.Leads
}

func (d *Data) GetConversions() *float64 {
	if d == nil {
		return nil
	}
	return d.Conversions
}

func (d *Data) GetSales() *float64 {
	if d == nil {
		return nil
	}
	return d.Sales
}

func (d *Data) GetSaleAmount() *float64 {
	if d == nil {
		return nil
	}
	return d.SaleAmount
}

func (d *Data) GetLastClicked() string {
	if d == nil {
		return ""
	}
	return d.LastClicked
}

func (d *Data) GetCreatedAt() string {
	if d == nil {
		return ""
	}
	return d.CreatedAt
}

func (d *Data) GetUpdatedAt() string {
	if d == nil {
		return ""
	}
	return d.UpdatedAt
}

func (d *Data) GetTagID() *string {
	if d == nil {
		return nil
	}
	return d.TagID
}

func (d *Data) GetProjectID() string {
	if d == nil {
		return ""
	}
	return d.ProjectID
}

// LinkWebhookEvent - Triggered when a link is created, updated, or deleted.
type LinkWebhookEvent struct {
	ID        string `json:"id"`
	Event     Event  `json:"event"`
	CreatedAt string `json:"createdAt"`
	Data      Data   `json:"data"`
}

func (l LinkWebhookEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LinkWebhookEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"id", "event", "createdAt", "data"}); err != nil {
		return err
	}
	return nil
}

func (l *LinkWebhookEvent) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *LinkWebhookEvent) GetEvent() Event {
	if l == nil {
		return Event{}
	}
	return l.Event
}

func (l *LinkWebhookEvent) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *LinkWebhookEvent) GetData() Data {
	if l == nil {
		return Data{}
	}
	return l.Data
}
