// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/dubinc/dub-go/internal/utils"
)

type ProgramApplicationSubmittedEventEvent string

const (
	ProgramApplicationSubmittedEventEventPartnerApplicationSubmitted ProgramApplicationSubmittedEventEvent = "partner.application_submitted"
)

func (e ProgramApplicationSubmittedEventEvent) ToPointer() *ProgramApplicationSubmittedEventEvent {
	return &e
}
func (e *ProgramApplicationSubmittedEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "partner.application_submitted":
		*e = ProgramApplicationSubmittedEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProgramApplicationSubmittedEventEvent: %v", v)
	}
}

// ProgramApplicationSubmittedEventStatus - The status of the partner's enrollment in the program.
type ProgramApplicationSubmittedEventStatus string

const (
	ProgramApplicationSubmittedEventStatusPending     ProgramApplicationSubmittedEventStatus = "pending"
	ProgramApplicationSubmittedEventStatusApproved    ProgramApplicationSubmittedEventStatus = "approved"
	ProgramApplicationSubmittedEventStatusRejected    ProgramApplicationSubmittedEventStatus = "rejected"
	ProgramApplicationSubmittedEventStatusInvited     ProgramApplicationSubmittedEventStatus = "invited"
	ProgramApplicationSubmittedEventStatusDeclined    ProgramApplicationSubmittedEventStatus = "declined"
	ProgramApplicationSubmittedEventStatusDeactivated ProgramApplicationSubmittedEventStatus = "deactivated"
	ProgramApplicationSubmittedEventStatusBanned      ProgramApplicationSubmittedEventStatus = "banned"
	ProgramApplicationSubmittedEventStatusArchived    ProgramApplicationSubmittedEventStatus = "archived"
)

func (e ProgramApplicationSubmittedEventStatus) ToPointer() *ProgramApplicationSubmittedEventStatus {
	return &e
}
func (e *ProgramApplicationSubmittedEventStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "pending":
		fallthrough
	case "approved":
		fallthrough
	case "rejected":
		fallthrough
	case "invited":
		fallthrough
	case "declined":
		fallthrough
	case "deactivated":
		fallthrough
	case "banned":
		fallthrough
	case "archived":
		*e = ProgramApplicationSubmittedEventStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ProgramApplicationSubmittedEventStatus: %v", v)
	}
}

type ProgramApplicationSubmittedEventPartner struct {
	// The partner's unique ID on Dub.
	ID string `json:"id"`
	// The partner's full legal name.
	Name string `json:"name"`
	// If the partner profile type is a company, this is the partner's legal company name.
	CompanyName *string `json:"companyName"`
	// The partner's email address. Should be a unique value across Dub.
	Email *string `json:"email"`
	// The partner's avatar image.
	Image *string `json:"image"`
	// A brief description of the partner and their background.
	Description *string `json:"description,omitempty"`
	// The partner's country (required for tax purposes).
	Country *string `json:"country"`
	// The partner's group ID on Dub.
	GroupID *string `json:"groupId,omitempty"`
	// The status of the partner's enrollment in the program.
	Status ProgramApplicationSubmittedEventStatus `json:"status"`
	// The partner's website URL (including the https protocol).
	Website *string `json:"website,omitempty"`
	// The partner's YouTube channel username (e.g. `johndoe`).
	Youtube *string `json:"youtube,omitempty"`
	// The partner's Twitter username (e.g. `johndoe`).
	Twitter *string `json:"twitter,omitempty"`
	// The partner's LinkedIn username (e.g. `johndoe`).
	Linkedin *string `json:"linkedin,omitempty"`
	// The partner's Instagram username (e.g. `johndoe`).
	Instagram *string `json:"instagram,omitempty"`
	// The partner's TikTok username (e.g. `johndoe`).
	Tiktok *string `json:"tiktok,omitempty"`
}

func (p ProgramApplicationSubmittedEventPartner) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProgramApplicationSubmittedEventPartner) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"id", "name", "status"}); err != nil {
		return err
	}
	return nil
}

func (p *ProgramApplicationSubmittedEventPartner) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *ProgramApplicationSubmittedEventPartner) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *ProgramApplicationSubmittedEventPartner) GetCompanyName() *string {
	if p == nil {
		return nil
	}
	return p.CompanyName
}

func (p *ProgramApplicationSubmittedEventPartner) GetEmail() *string {
	if p == nil {
		return nil
	}
	return p.Email
}

func (p *ProgramApplicationSubmittedEventPartner) GetImage() *string {
	if p == nil {
		return nil
	}
	return p.Image
}

func (p *ProgramApplicationSubmittedEventPartner) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *ProgramApplicationSubmittedEventPartner) GetCountry() *string {
	if p == nil {
		return nil
	}
	return p.Country
}

func (p *ProgramApplicationSubmittedEventPartner) GetGroupID() *string {
	if p == nil {
		return nil
	}
	return p.GroupID
}

func (p *ProgramApplicationSubmittedEventPartner) GetStatus() ProgramApplicationSubmittedEventStatus {
	if p == nil {
		return ProgramApplicationSubmittedEventStatus("")
	}
	return p.Status
}

func (p *ProgramApplicationSubmittedEventPartner) GetWebsite() *string {
	if p == nil {
		return nil
	}
	return p.Website
}

func (p *ProgramApplicationSubmittedEventPartner) GetYoutube() *string {
	if p == nil {
		return nil
	}
	return p.Youtube
}

func (p *ProgramApplicationSubmittedEventPartner) GetTwitter() *string {
	if p == nil {
		return nil
	}
	return p.Twitter
}

func (p *ProgramApplicationSubmittedEventPartner) GetLinkedin() *string {
	if p == nil {
		return nil
	}
	return p.Linkedin
}

func (p *ProgramApplicationSubmittedEventPartner) GetInstagram() *string {
	if p == nil {
		return nil
	}
	return p.Instagram
}

func (p *ProgramApplicationSubmittedEventPartner) GetTiktok() *string {
	if p == nil {
		return nil
	}
	return p.Tiktok
}

type ApplicationFormData struct {
	Label string  `json:"label"`
	Value *string `json:"value"`
}

func (a ApplicationFormData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ApplicationFormData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, []string{"label"}); err != nil {
		return err
	}
	return nil
}

func (a *ApplicationFormData) GetLabel() string {
	if a == nil {
		return ""
	}
	return a.Label
}

func (a *ApplicationFormData) GetValue() *string {
	if a == nil {
		return nil
	}
	return a.Value
}

type ProgramApplicationSubmittedEventData struct {
	ID                  string                                  `json:"id"`
	CreatedAt           string                                  `json:"createdAt"`
	Partner             ProgramApplicationSubmittedEventPartner `json:"partner"`
	ApplicationFormData []ApplicationFormData                   `json:"applicationFormData"`
}

func (p ProgramApplicationSubmittedEventData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProgramApplicationSubmittedEventData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"id", "createdAt", "partner"}); err != nil {
		return err
	}
	return nil
}

func (p *ProgramApplicationSubmittedEventData) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *ProgramApplicationSubmittedEventData) GetCreatedAt() string {
	if p == nil {
		return ""
	}
	return p.CreatedAt
}

func (p *ProgramApplicationSubmittedEventData) GetPartner() ProgramApplicationSubmittedEventPartner {
	if p == nil {
		return ProgramApplicationSubmittedEventPartner{}
	}
	return p.Partner
}

func (p *ProgramApplicationSubmittedEventData) GetApplicationFormData() []ApplicationFormData {
	if p == nil {
		return nil
	}
	return p.ApplicationFormData
}

// ProgramApplicationSubmittedEvent - Triggered when a partner submits an application to join a program.
type ProgramApplicationSubmittedEvent struct {
	ID        string                                `json:"id"`
	Event     ProgramApplicationSubmittedEventEvent `json:"event"`
	CreatedAt string                                `json:"createdAt"`
	Data      ProgramApplicationSubmittedEventData  `json:"data"`
}

func (p ProgramApplicationSubmittedEvent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProgramApplicationSubmittedEvent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"id", "event", "createdAt", "data"}); err != nil {
		return err
	}
	return nil
}

func (p *ProgramApplicationSubmittedEvent) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *ProgramApplicationSubmittedEvent) GetEvent() ProgramApplicationSubmittedEventEvent {
	if p == nil {
		return ProgramApplicationSubmittedEventEvent("")
	}
	return p.Event
}

func (p *ProgramApplicationSubmittedEvent) GetCreatedAt() string {
	if p == nil {
		return ""
	}
	return p.CreatedAt
}

func (p *ProgramApplicationSubmittedEvent) GetData() ProgramApplicationSubmittedEventData {
	if p == nil {
		return ProgramApplicationSubmittedEventData{}
	}
	return p.Data
}
