// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/dubinc/dub-go/internal/utils"
)

type SaleEventEvent string

const (
	SaleEventEventSale SaleEventEvent = "sale"
)

func (e SaleEventEvent) ToPointer() *SaleEventEvent {
	return &e
}
func (e *SaleEventEvent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sale":
		*e = SaleEventEvent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SaleEventEvent: %v", v)
	}
}

// PaymentProcessor - The payment processor via which the sale was made.
type PaymentProcessor string

const (
	PaymentProcessorStripe     PaymentProcessor = "stripe"
	PaymentProcessorShopify    PaymentProcessor = "shopify"
	PaymentProcessorPolar      PaymentProcessor = "polar"
	PaymentProcessorPaddle     PaymentProcessor = "paddle"
	PaymentProcessorRevenuecat PaymentProcessor = "revenuecat"
	PaymentProcessorCustom     PaymentProcessor = "custom"
)

func (e PaymentProcessor) ToPointer() *PaymentProcessor {
	return &e
}
func (e *PaymentProcessor) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stripe":
		fallthrough
	case "shopify":
		fallthrough
	case "polar":
		fallthrough
	case "paddle":
		fallthrough
	case "revenuecat":
		fallthrough
	case "custom":
		*e = PaymentProcessor(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentProcessor: %v", v)
	}
}

type Sale struct {
	// The amount of the sale in cents (for all two-decimal currencies). If the sale is in a zero-decimal currency, pass the full integer value (e.g. `1437` JPY). Learn more: https://d.to/currency
	Amount int64 `json:"amount"`
	// The invoice ID of the sale. Can be used as a idempotency key – only one sale event can be recorded for a given invoice ID.
	InvoiceID *string `default:"null" json:"invoiceId"`
	// The payment processor via which the sale was made.
	PaymentProcessor PaymentProcessor `json:"paymentProcessor"`
}

func (s Sale) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Sale) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Sale) GetAmount() int64 {
	if o == nil {
		return 0
	}
	return o.Amount
}

func (o *Sale) GetInvoiceID() *string {
	if o == nil {
		return nil
	}
	return o.InvoiceID
}

func (o *Sale) GetPaymentProcessor() PaymentProcessor {
	if o == nil {
		return PaymentProcessor("")
	}
	return o.PaymentProcessor
}

type SaleEventTestVariants struct {
	URL        string  `json:"url"`
	Percentage float64 `json:"percentage"`
}

func (o *SaleEventTestVariants) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *SaleEventTestVariants) GetPercentage() float64 {
	if o == nil {
		return 0.0
	}
	return o.Percentage
}

type SaleEventLink struct {
	// The unique ID of the short link.
	ID string `json:"id"`
	// The domain of the short link. If not provided, the primary domain for the workspace will be used (or `dub.sh` if the workspace has no domains).
	Domain string `json:"domain"`
	// The short link slug. If not provided, a random 7-character slug will be generated.
	Key             string `json:"key"`
	URL             string `json:"url"`
	TrackConversion bool   `json:"trackConversion"`
	// The ID of the link in your database. If set, it can be used to identify the link in future API requests (must be prefixed with 'ext_' when passed as a query parameter). This key is unique across your workspace.
	ExternalID *string `json:"externalId"`
	// The ID of the tenant that created the link inside your system. If set, it can be used to fetch all links for a tenant.
	TenantID *string `json:"tenantId"`
	// The ID of the program the short link is associated with.
	ProgramID *string `json:"programId"`
	// The ID of the partner the short link is associated with.
	PartnerID  *string `json:"partnerId"`
	Archived   bool    `json:"archived"`
	ExpiresAt  string  `json:"expiresAt"`
	ExpiredURL *string `json:"expiredUrl"`
	// The password required to access the destination URL of the short link.
	Password *string `json:"password"`
	Proxy    bool    `json:"proxy"`
	// The title of the short link. Will be used for Custom Link Previews if `proxy` is true.
	Title *string `json:"title"`
	// The description of the short link. Will be used for Custom Link Previews if `proxy` is true.
	Description *string `json:"description"`
	// The image of the short link. Will be used for Custom Link Previews if `proxy` is true.
	Image *string `json:"image"`
	// The custom link preview video (og:video). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
	Video   *string `json:"video"`
	Rewrite bool    `json:"rewrite"`
	DoIndex bool    `json:"doIndex"`
	// The iOS destination URL for the short link for iOS device targeting.
	Ios *string `json:"ios"`
	// The Android destination URL for the short link for Android device targeting.
	Android *string `json:"android"`
	// Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`. See https://d.to/geo for more information.
	Geo         map[string]string `json:"geo"`
	PublicStats bool              `json:"publicStats"`
	// The tags assigned to the short link.
	Tags []TagSchema `json:"tags"`
	// The unique ID of the folder assigned to the short link.
	FolderID *string `json:"folderId"`
	// The IDs of the webhooks that the short link is associated with.
	WebhookIds []string `json:"webhookIds"`
	// The comments for the short link.
	Comments *string `json:"comments"`
	// The full URL of the short link, including the https protocol (e.g. `https://dub.sh/try`).
	ShortLink string `json:"shortLink"`
	// The full URL of the QR code for the short link (e.g. `https://api.dub.co/qr?url=https://dub.sh/try`).
	QrCode string `json:"qrCode"`
	// The UTM source of the short link.
	UtmSource *string `json:"utm_source"`
	// The UTM medium of the short link.
	UtmMedium *string `json:"utm_medium"`
	// The UTM campaign of the short link.
	UtmCampaign *string `json:"utm_campaign"`
	// The UTM term of the short link.
	UtmTerm *string `json:"utm_term"`
	// The UTM content of the short link.
	UtmContent *string `json:"utm_content"`
	// An array of A/B test URLs and the percentage of traffic to send to each URL.
	TestVariants    []SaleEventTestVariants `json:"testVariants,omitempty"`
	TestStartedAt   *string                 `json:"testStartedAt"`
	TestCompletedAt *string                 `json:"testCompletedAt"`
	UserID          *string                 `json:"userId"`
	// The workspace ID of the short link.
	WorkspaceID string `json:"workspaceId"`
	// The number of clicks on the short link.
	Clicks *float64 `default:"0" json:"clicks"`
	// The number of leads the short link has generated.
	Leads *float64 `default:"0" json:"leads"`
	// The number of leads that converted to paying customers.
	Conversions *float64 `default:"0" json:"conversions"`
	// The total number of sales (includes recurring sales) generated by the short link.
	Sales *float64 `default:"0" json:"sales"`
	// The total dollar value of sales (in cents) generated by the short link.
	SaleAmount  *float64 `default:"0" json:"saleAmount"`
	LastClicked string   `json:"lastClicked"`
	CreatedAt   string   `json:"createdAt"`
	UpdatedAt   string   `json:"updatedAt"`
	// Deprecated: Use `tags` instead. The unique ID of the tag assigned to the short link.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	TagID *string `json:"tagId"`
	// Deprecated: Use `workspaceId` instead. The project ID of the short link.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ProjectID string `json:"projectId"`
}

func (s SaleEventLink) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SaleEventLink) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SaleEventLink) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *SaleEventLink) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}

func (o *SaleEventLink) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *SaleEventLink) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *SaleEventLink) GetTrackConversion() bool {
	if o == nil {
		return false
	}
	return o.TrackConversion
}

func (o *SaleEventLink) GetExternalID() *string {
	if o == nil {
		return nil
	}
	return o.ExternalID
}

func (o *SaleEventLink) GetTenantID() *string {
	if o == nil {
		return nil
	}
	return o.TenantID
}

func (o *SaleEventLink) GetProgramID() *string {
	if o == nil {
		return nil
	}
	return o.ProgramID
}

func (o *SaleEventLink) GetPartnerID() *string {
	if o == nil {
		return nil
	}
	return o.PartnerID
}

func (o *SaleEventLink) GetArchived() bool {
	if o == nil {
		return false
	}
	return o.Archived
}

func (o *SaleEventLink) GetExpiresAt() string {
	if o == nil {
		return ""
	}
	return o.ExpiresAt
}

func (o *SaleEventLink) GetExpiredURL() *string {
	if o == nil {
		return nil
	}
	return o.ExpiredURL
}

func (o *SaleEventLink) GetPassword() *string {
	if o == nil {
		return nil
	}
	return o.Password
}

func (o *SaleEventLink) GetProxy() bool {
	if o == nil {
		return false
	}
	return o.Proxy
}

func (o *SaleEventLink) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *SaleEventLink) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *SaleEventLink) GetImage() *string {
	if o == nil {
		return nil
	}
	return o.Image
}

func (o *SaleEventLink) GetVideo() *string {
	if o == nil {
		return nil
	}
	return o.Video
}

func (o *SaleEventLink) GetRewrite() bool {
	if o == nil {
		return false
	}
	return o.Rewrite
}

func (o *SaleEventLink) GetDoIndex() bool {
	if o == nil {
		return false
	}
	return o.DoIndex
}

func (o *SaleEventLink) GetIos() *string {
	if o == nil {
		return nil
	}
	return o.Ios
}

func (o *SaleEventLink) GetAndroid() *string {
	if o == nil {
		return nil
	}
	return o.Android
}

func (o *SaleEventLink) GetGeo() map[string]string {
	if o == nil {
		return nil
	}
	return o.Geo
}

func (o *SaleEventLink) GetPublicStats() bool {
	if o == nil {
		return false
	}
	return o.PublicStats
}

func (o *SaleEventLink) GetTags() []TagSchema {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *SaleEventLink) GetFolderID() *string {
	if o == nil {
		return nil
	}
	return o.FolderID
}

func (o *SaleEventLink) GetWebhookIds() []string {
	if o == nil {
		return []string{}
	}
	return o.WebhookIds
}

func (o *SaleEventLink) GetComments() *string {
	if o == nil {
		return nil
	}
	return o.Comments
}

func (o *SaleEventLink) GetShortLink() string {
	if o == nil {
		return ""
	}
	return o.ShortLink
}

func (o *SaleEventLink) GetQrCode() string {
	if o == nil {
		return ""
	}
	return o.QrCode
}

func (o *SaleEventLink) GetUtmSource() *string {
	if o == nil {
		return nil
	}
	return o.UtmSource
}

func (o *SaleEventLink) GetUtmMedium() *string {
	if o == nil {
		return nil
	}
	return o.UtmMedium
}

func (o *SaleEventLink) GetUtmCampaign() *string {
	if o == nil {
		return nil
	}
	return o.UtmCampaign
}

func (o *SaleEventLink) GetUtmTerm() *string {
	if o == nil {
		return nil
	}
	return o.UtmTerm
}

func (o *SaleEventLink) GetUtmContent() *string {
	if o == nil {
		return nil
	}
	return o.UtmContent
}

func (o *SaleEventLink) GetTestVariants() []SaleEventTestVariants {
	if o == nil {
		return nil
	}
	return o.TestVariants
}

func (o *SaleEventLink) GetTestStartedAt() *string {
	if o == nil {
		return nil
	}
	return o.TestStartedAt
}

func (o *SaleEventLink) GetTestCompletedAt() *string {
	if o == nil {
		return nil
	}
	return o.TestCompletedAt
}

func (o *SaleEventLink) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *SaleEventLink) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *SaleEventLink) GetClicks() *float64 {
	if o == nil {
		return nil
	}
	return o.Clicks
}

func (o *SaleEventLink) GetLeads() *float64 {
	if o == nil {
		return nil
	}
	return o.Leads
}

func (o *SaleEventLink) GetConversions() *float64 {
	if o == nil {
		return nil
	}
	return o.Conversions
}

func (o *SaleEventLink) GetSales() *float64 {
	if o == nil {
		return nil
	}
	return o.Sales
}

func (o *SaleEventLink) GetSaleAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.SaleAmount
}

func (o *SaleEventLink) GetLastClicked() string {
	if o == nil {
		return ""
	}
	return o.LastClicked
}

func (o *SaleEventLink) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *SaleEventLink) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *SaleEventLink) GetTagID() *string {
	if o == nil {
		return nil
	}
	return o.TagID
}

func (o *SaleEventLink) GetProjectID() string {
	if o == nil {
		return ""
	}
	return o.ProjectID
}

type SaleEventClick struct {
	ID         string  `json:"id"`
	Timestamp  string  `json:"timestamp"`
	URL        string  `json:"url"`
	Country    string  `json:"country"`
	City       string  `json:"city"`
	Region     string  `json:"region"`
	Continent  string  `json:"continent"`
	Device     string  `json:"device"`
	Browser    string  `json:"browser"`
	Os         string  `json:"os"`
	Trigger    *string `json:"trigger,omitempty"`
	Referer    string  `json:"referer"`
	RefererURL string  `json:"refererUrl"`
	Qr         bool    `json:"qr"`
	IP         string  `json:"ip"`
}

func (o *SaleEventClick) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *SaleEventClick) GetTimestamp() string {
	if o == nil {
		return ""
	}
	return o.Timestamp
}

func (o *SaleEventClick) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *SaleEventClick) GetCountry() string {
	if o == nil {
		return ""
	}
	return o.Country
}

func (o *SaleEventClick) GetCity() string {
	if o == nil {
		return ""
	}
	return o.City
}

func (o *SaleEventClick) GetRegion() string {
	if o == nil {
		return ""
	}
	return o.Region
}

func (o *SaleEventClick) GetContinent() string {
	if o == nil {
		return ""
	}
	return o.Continent
}

func (o *SaleEventClick) GetDevice() string {
	if o == nil {
		return ""
	}
	return o.Device
}

func (o *SaleEventClick) GetBrowser() string {
	if o == nil {
		return ""
	}
	return o.Browser
}

func (o *SaleEventClick) GetOs() string {
	if o == nil {
		return ""
	}
	return o.Os
}

func (o *SaleEventClick) GetTrigger() *string {
	if o == nil {
		return nil
	}
	return o.Trigger
}

func (o *SaleEventClick) GetReferer() string {
	if o == nil {
		return ""
	}
	return o.Referer
}

func (o *SaleEventClick) GetRefererURL() string {
	if o == nil {
		return ""
	}
	return o.RefererURL
}

func (o *SaleEventClick) GetQr() bool {
	if o == nil {
		return false
	}
	return o.Qr
}

func (o *SaleEventClick) GetIP() string {
	if o == nil {
		return ""
	}
	return o.IP
}

type SaleEventCustomer struct {
	// The unique ID of the customer. You may use either the customer's `id` on Dub (obtained via `/customers` endpoint) or their `externalId` (unique ID within your system, prefixed with `ext_`, e.g. `ext_123`).
	ID string `json:"id"`
	// Unique identifier for the customer in the client's app.
	ExternalID string `json:"externalId"`
	// Name of the customer.
	Name string `json:"name"`
	// Email of the customer.
	Email *string `json:"email,omitempty"`
	// Avatar URL of the customer.
	Avatar *string `json:"avatar,omitempty"`
	// Country of the customer.
	Country *string `json:"country,omitempty"`
	// Total number of sales for the customer.
	Sales *float64 `json:"sales,omitempty"`
	// Total amount of sales for the customer.
	SaleAmount *float64 `json:"saleAmount,omitempty"`
	// The date the customer was created.
	CreatedAt string `json:"createdAt"`
}

func (o *SaleEventCustomer) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *SaleEventCustomer) GetExternalID() string {
	if o == nil {
		return ""
	}
	return o.ExternalID
}

func (o *SaleEventCustomer) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SaleEventCustomer) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *SaleEventCustomer) GetAvatar() *string {
	if o == nil {
		return nil
	}
	return o.Avatar
}

func (o *SaleEventCustomer) GetCountry() *string {
	if o == nil {
		return nil
	}
	return o.Country
}

func (o *SaleEventCustomer) GetSales() *float64 {
	if o == nil {
		return nil
	}
	return o.Sales
}

func (o *SaleEventCustomer) GetSaleAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.SaleAmount
}

func (o *SaleEventCustomer) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

type SaleEvent struct {
	Event     SaleEventEvent    `json:"event"`
	Timestamp string            `json:"timestamp"`
	EventID   string            `json:"eventId"`
	EventName string            `json:"eventName"`
	Sale      Sale              `json:"sale"`
	Metadata  any               `json:"metadata,omitempty"`
	Link      SaleEventLink     `json:"link"`
	Click     SaleEventClick    `json:"click"`
	Customer  SaleEventCustomer `json:"customer"`
	// Deprecated: Use `sale.amount` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	SaleAmount float64 `json:"saleAmount"`
	// Deprecated: Use `sale.invoiceId` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	InvoiceID string `json:"invoice_id"`
	// Deprecated: Use `sale.paymentProcessor` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	PaymentProcessor string `json:"payment_processor"`
	// Deprecated: Use `click.id` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ClickID string `json:"click_id"`
	// Deprecated: Use `link.id` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	LinkID string `json:"link_id"`
	// Deprecated: Use `link.domain` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Domain string `json:"domain"`
	// Deprecated: Use `link.key` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Key string `json:"key"`
	// Deprecated: Use `click.url` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	URL string `json:"url"`
	// Deprecated: Use `click.continent` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Continent string `json:"continent"`
	// Deprecated: Use `click.country` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Country string `json:"country"`
	// Deprecated: Use `click.city` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	City string `json:"city"`
	// Deprecated: Use `click.device` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Device string `json:"device"`
	// Deprecated: Use `click.browser` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Browser string `json:"browser"`
	// Deprecated: Use `click.os` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Os string `json:"os"`
	// Deprecated: Use `click.qr` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Qr float64 `json:"qr"`
	// Deprecated: Use `click.ip` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	IP string `json:"ip"`
}

func (o *SaleEvent) GetEvent() SaleEventEvent {
	if o == nil {
		return SaleEventEvent("")
	}
	return o.Event
}

func (o *SaleEvent) GetTimestamp() string {
	if o == nil {
		return ""
	}
	return o.Timestamp
}

func (o *SaleEvent) GetEventID() string {
	if o == nil {
		return ""
	}
	return o.EventID
}

func (o *SaleEvent) GetEventName() string {
	if o == nil {
		return ""
	}
	return o.EventName
}

func (o *SaleEvent) GetSale() Sale {
	if o == nil {
		return Sale{}
	}
	return o.Sale
}

func (o *SaleEvent) GetMetadata() any {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *SaleEvent) GetLink() SaleEventLink {
	if o == nil {
		return SaleEventLink{}
	}
	return o.Link
}

func (o *SaleEvent) GetClick() SaleEventClick {
	if o == nil {
		return SaleEventClick{}
	}
	return o.Click
}

func (o *SaleEvent) GetCustomer() SaleEventCustomer {
	if o == nil {
		return SaleEventCustomer{}
	}
	return o.Customer
}

func (o *SaleEvent) GetSaleAmount() float64 {
	if o == nil {
		return 0.0
	}
	return o.SaleAmount
}

func (o *SaleEvent) GetInvoiceID() string {
	if o == nil {
		return ""
	}
	return o.InvoiceID
}

func (o *SaleEvent) GetPaymentProcessor() string {
	if o == nil {
		return ""
	}
	return o.PaymentProcessor
}

func (o *SaleEvent) GetClickID() string {
	if o == nil {
		return ""
	}
	return o.ClickID
}

func (o *SaleEvent) GetLinkID() string {
	if o == nil {
		return ""
	}
	return o.LinkID
}

func (o *SaleEvent) GetDomain() string {
	if o == nil {
		return ""
	}
	return o.Domain
}

func (o *SaleEvent) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *SaleEvent) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

func (o *SaleEvent) GetContinent() string {
	if o == nil {
		return ""
	}
	return o.Continent
}

func (o *SaleEvent) GetCountry() string {
	if o == nil {
		return ""
	}
	return o.Country
}

func (o *SaleEvent) GetCity() string {
	if o == nil {
		return ""
	}
	return o.City
}

func (o *SaleEvent) GetDevice() string {
	if o == nil {
		return ""
	}
	return o.Device
}

func (o *SaleEvent) GetBrowser() string {
	if o == nil {
		return ""
	}
	return o.Browser
}

func (o *SaleEvent) GetOs() string {
	if o == nil {
		return ""
	}
	return o.Os
}

func (o *SaleEvent) GetQr() float64 {
	if o == nil {
		return 0.0
	}
	return o.Qr
}

func (o *SaleEvent) GetIP() string {
	if o == nil {
		return ""
	}
	return o.IP
}
