workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    dub:
        inputs:
            - location: https://api.dub.co
        registry:
            location: registry.speakeasyapi.dev/dub/dub/dub
targets:
    my-first-target:
        target: go
        source: dub
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/dub/dub/code-samples-go-my-first-target
